package ucr.casoUso;

import java.util.ArrayList;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;

public class VistaLogs extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button botonVolver;
	@AutoGenerated
	private Label labelNumero;
	@AutoGenerated
	private Label labelTitulo;
	@AutoGenerated
	private Table table_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	
	Controlador control;
	ControladorLogs controlador;
	
	public VistaLogs() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		controlador = ControladorLogs.obtenerInstancia();
		control = Controlador.obtenerInstancia();
		labelNumero.setValue(controlador.getNumExp());
		llenarTabla();
		botonVolver.addClickListener(new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				control.cambiarVista("Expediente", controlador.getCodExp());
			}
		});
	}
	
	public void llenarTabla(){
		ArrayList<String[]> resultados = controlador.pedirDatos();
		table_1.addContainerProperty("#", String.class, null);
		table_1.addContainerProperty("Usuario", String.class, null);
		table_1.addContainerProperty("Fecha", String.class, null);
		table_1.addContainerProperty("Campo", String.class, null);
		table_1.addContainerProperty("Estado Anterior", String.class, null);
		table_1.addContainerProperty("Estado Actual", String.class, null);
		for(int i = 0; i < resultados.size(); i++){
			String[] tupla = resultados.get(i);
			System.out.println(tupla[0] + tupla[1] + tupla[2] + tupla[3] + tupla[4] + tupla[5]);
			table_1.addItem(new Object[]{tupla[0], tupla[1], tupla[2], tupla[3], tupla[4], tupla[5]}, (i +1));
		}
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setCaption("asds");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// table_1
		table_1 = new Table();
		table_1.setImmediate(false);
		table_1.setWidth("-1px");
		table_1.setHeight("223px");
		mainLayout.addComponent(table_1, "top:57.0px;left:40.0px;");
		
		// labelTitulo
		labelTitulo = new Label();
		labelTitulo.setImmediate(false);
		labelTitulo.setWidth("340px");
		labelTitulo.setHeight("18px");
		labelTitulo.setValue("Registro de cambios de expediente #");
		mainLayout.addComponent(labelTitulo, "top:20.0px;left:40.0px;");
		
		// labelNumero
		labelNumero = new Label();
		labelNumero.setImmediate(false);
		labelNumero.setWidth("-1px");
		labelNumero.setHeight("-1px");
		labelNumero.setValue("(Numero)");
		mainLayout.addComponent(labelNumero, "top:20.0px;left:309.0px;");
		
		// botonVolver
		botonVolver = new Button();
		botonVolver.setCaption("Volver");
		botonVolver.setImmediate(true);
		botonVolver.setWidth("-1px");
		botonVolver.setHeight("-1px");
		mainLayout.addComponent(botonVolver, "top:300.0px;left:40.0px;");
		
		return mainLayout;
	}

}
