package ucr.casoUso;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;

public class VistaExpediente extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button botonVolver;
	@AutoGenerated
	private Button botonArchivar;
	@AutoGenerated
	private Button botonLog;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private Label valorEstado;
	@AutoGenerated
	private Label labelEstado;
	@AutoGenerated
	private Label valorInstAsig;
	@AutoGenerated
	private Label labelInstAsig;
	@AutoGenerated
	private Label valorNumExpediente;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public VistaExpediente() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		valorInstAsig.setValue("1");
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// valorNumExpediente
		valorNumExpediente = new Label();
		valorNumExpediente.setStyleName("titulo");
		valorNumExpediente.setImmediate(false);
		valorNumExpediente.setWidth("-1px");
		valorNumExpediente.setHeight("-1px");
		valorNumExpediente.setValue("Expediente");
		mainLayout.addComponent(valorNumExpediente, "top:62.0px;left:60.0px;");
		
		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		mainLayout.addComponent(gridLayout_1, "top:122.0px;left:80.0px;");
		
		// botonLog
		botonLog = new Button();
		botonLog.setCaption("Registro");
		botonLog.setImmediate(false);
		botonLog.setWidth("-1px");
		botonLog.setHeight("-1px");
		mainLayout.addComponent(botonLog, "top:60.0px;left:360.0px;");
		
		// botonArchivar
		botonArchivar = new Button();
		botonArchivar.setCaption("Archivar");
		botonArchivar.setImmediate(false);
		botonArchivar.setWidth("-1px");
		botonArchivar.setHeight("-1px");
		mainLayout.addComponent(botonArchivar, "top:60.0px;left:465.0px;");
		
		// botonVolver
		botonVolver = new Button();
		botonVolver.setCaption("Volver");
		botonVolver.setImmediate(false);
		botonVolver.setWidth("-1px");
		botonVolver.setHeight("-1px");
		mainLayout.addComponent(botonVolver, "top:60.0px;left:576.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("-1px");
		gridLayout_1.setHeight("-1px");
		gridLayout_1.setMargin(false);
		gridLayout_1.setSpacing(true);
		gridLayout_1.setColumns(6);
		
		// labelInstAsig
		labelInstAsig = new Label();
		labelInstAsig.setImmediate(false);
		labelInstAsig.setWidth("-1px");
		labelInstAsig.setHeight("-1px");
		labelInstAsig.setValue("Instructor Asignado:");
		gridLayout_1.addComponent(labelInstAsig, 0, 0);
		
		// valorInstAsig
		valorInstAsig = new Label();
		valorInstAsig.setImmediate(false);
		valorInstAsig.setWidth("-1px");
		valorInstAsig.setHeight("-1px");
		valorInstAsig.setValue("valorInst");
		gridLayout_1.addComponent(valorInstAsig, 1, 0);
		
		// labelEstado
		labelEstado = new Label();
		labelEstado.setImmediate(false);
		labelEstado.setWidth("-1px");
		labelEstado.setHeight("-1px");
		labelEstado.setValue("Estado:");
		gridLayout_1.addComponent(labelEstado, 4, 0);
		
		// valorEstado
		valorEstado = new Label();
		valorEstado.setImmediate(false);
		valorEstado.setWidth("-1px");
		valorEstado.setHeight("-1px");
		valorEstado.setValue("valorEst");
		gridLayout_1.addComponent(valorEstado, 5, 0);
		
		return gridLayout_1;
	}

}
