package ucr.casoUso;

import java.util.HashMap;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;

public class VistaExpediente extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Accordion Acordeon;
	@AutoGenerated
	private AbsoluteLayout LayoutFechas;
	@AutoGenerated
	private Button botonEnvDuracCambioUltUbic;
	@AutoGenerated
	private TextField campoDuracCambioUltUbic;
	@AutoGenerated
	private Button botonModDuracCambioUltUbic;
	@AutoGenerated
	private Label valorDuracCambioUltUbic;
	@AutoGenerated
	private Label labelDuracCambioUltUbic;
	@AutoGenerated
	private Button botonEnvPlazoIngresoUltUbic;
	@AutoGenerated
	private TextField campoPlazoIngresoUltUbic;
	@AutoGenerated
	private Button botonModPlazoIngresoUltUbic;
	@AutoGenerated
	private Label valorPlazoIngresoUltUbic;
	@AutoGenerated
	private Label labelPlazoIngresoUltUbic;
	@AutoGenerated
	private Button botonEnvFechaIng;
	@AutoGenerated
	private TextField campoFechaIng;
	@AutoGenerated
	private Button botonModFechaIng;
	@AutoGenerated
	private Label valorFechaIng;
	@AutoGenerated
	private Label labelFechaIng;
	@AutoGenerated
	private Button botonEnvDuracIngresoUltUbic;
	@AutoGenerated
	private TextField campoDuracIngresoUltUbic;
	@AutoGenerated
	private Button botonModDuracIngresoUltUbic;
	@AutoGenerated
	private Label valorDuracIngresoUltUbic;
	@AutoGenerated
	private Label labelDuracIngresoUltUbic;
	@AutoGenerated
	private Button botonEnvPlazoIngresoCambio;
	@AutoGenerated
	private TextField campoPlazoIngresoCambio;
	@AutoGenerated
	private Button botonModPlazoIngresoCambio;
	@AutoGenerated
	private Label valorPlazoIngresoCambio;
	@AutoGenerated
	private Label labelPlazoIngresoCambio;
	@AutoGenerated
	private Button botonEnvDuracIngresoCambio;
	@AutoGenerated
	private TextField campoDuracIngresoCambio;
	@AutoGenerated
	private Button botonModDuracIngresoCambio;
	@AutoGenerated
	private Label valorDuracIngresoCambio;
	@AutoGenerated
	private Label labelDuracIngresoCambio;
	@AutoGenerated
	private Button botonEnvDuracPresentacionIngreso;
	@AutoGenerated
	private TextField campoDuracPresentacionIngreso;
	@AutoGenerated
	private Button botonModDuracPresentacionIngreso;
	@AutoGenerated
	private Label valorDuracPresentacionIngreso;
	@AutoGenerated
	private Label labelDuracPresentacionIngreso;
	@AutoGenerated
	private Button botonEnvFechaPresentacion;
	@AutoGenerated
	private TextField campoFechaPresentacion;
	@AutoGenerated
	private Button botonModFechaPresentacion;
	@AutoGenerated
	private Label valorFechaPresentacion;
	@AutoGenerated
	private Label labelFechaPresentacion;
	@AutoGenerated
	private Button botonEnvFechaUltUbicacion;
	@AutoGenerated
	private TextField campoFechaUltUbicacion;
	@AutoGenerated
	private Button botonModFechaUltUbicacion;
	@AutoGenerated
	private Label valorFechaUltUbicacion;
	@AutoGenerated
	private Label labelFechaUltUbicacion;
	@AutoGenerated
	private Button botonEnvFechaCambioEstado;
	@AutoGenerated
	private TextField campoFechaCambioEstado;
	@AutoGenerated
	private Button botonModFechaCambioEstado;
	@AutoGenerated
	private Label valorFechaCambioEstado;
	@AutoGenerated
	private Label labelFechaCambioEstado;
	@AutoGenerated
	private AbsoluteLayout LayoutUbicacion;
	@AutoGenerated
	private Button botonEnvCantLegajos;
	@AutoGenerated
	private TextField campoCantLegajos;
	@AutoGenerated
	private Button botonModCantLegajos;
	@AutoGenerated
	private Label valorCantLegajos;
	@AutoGenerated
	private Label labelCantLegajos;
	@AutoGenerated
	private Button botonEnvUbicLegajos;
	@AutoGenerated
	private TextField campoUbicLegajos;
	@AutoGenerated
	private Button botonModUbicLegajos;
	@AutoGenerated
	private Label valorUbicLegajos;
	@AutoGenerated
	private Label labelUbicLegajos;
	@AutoGenerated
	private Button botonEnvMuebleUbicacion;
	@AutoGenerated
	private TextField campoMuebleUbicacion;
	@AutoGenerated
	private Button botonModMuebleUbicacion;
	@AutoGenerated
	private Label valorMuebleUbicacion;
	@AutoGenerated
	private Label labelMuebleUbicacion;
	@AutoGenerated
	private Button botonEnvUbicacion;
	@AutoGenerated
	private TextField campoUbicacion;
	@AutoGenerated
	private Button botonModUbicacion;
	@AutoGenerated
	private Label valorUbicacion;
	@AutoGenerated
	private Label labelUbicacion;
	@AutoGenerated
	private AbsoluteLayout LayoutPlazo;
	@AutoGenerated
	private Button botonEnvCondPlazo;
	@AutoGenerated
	private TextField campoCondPlazo;
	@AutoGenerated
	private Button botonModCondPlazo;
	@AutoGenerated
	private Label valorCondPlazo;
	@AutoGenerated
	private Label labelCondPlazo;
	@AutoGenerated
	private Button botonEnvTiempoTranscurrido;
	@AutoGenerated
	private TextField campoTiempoTranscurrido;
	@AutoGenerated
	private Button botonModTiempoTranscurrido;
	@AutoGenerated
	private Label valorTiempoTranscurrido;
	@AutoGenerated
	private Label labelTiempoTranscurrido;
	@AutoGenerated
	private Button botonEnvPlazo;
	@AutoGenerated
	private TextField campoPlazo;
	@AutoGenerated
	private Button botonModPlazo;
	@AutoGenerated
	private Label valorPlazo;
	@AutoGenerated
	private Label labelPlazo;
	@AutoGenerated
	private AbsoluteLayout LayoutInfoDenuncia;
	@AutoGenerated
	private Button botonEnvHoraAudiencia;
	@AutoGenerated
	private TextField campoHoraAudiencia;
	@AutoGenerated
	private Button botonModHoraAudiencia;
	@AutoGenerated
	private Label valorHoraAudiencia;
	@AutoGenerated
	private Label labelHoraAudiencia;
	@AutoGenerated
	private Button botonEnvFechaAudiencia;
	@AutoGenerated
	private TextField campoFechaAudiencia;
	@AutoGenerated
	private Button botonModFechaAudiencia;
	@AutoGenerated
	private Label valorFechaAudiencia;
	@AutoGenerated
	private Label labelFechaAudiencia;
	@AutoGenerated
	private Button botonEnvArtAplicables;
	@AutoGenerated
	private TextField campoArtAplicables;
	@AutoGenerated
	private Button botonModArtAplicables;
	@AutoGenerated
	private Label valorArtAplicables;
	@AutoGenerated
	private Label labelArtAplicables;
	@AutoGenerated
	private Button botonEnvCausa;
	@AutoGenerated
	private Button botonModCausa;
	@AutoGenerated
	private TextField campoCausa;
	@AutoGenerated
	private Label valorCausa;
	@AutoGenerated
	private Label labelCausa;
	@AutoGenerated
	private Button botonEnvId;
	@AutoGenerated
	private TextField campoId;
	@AutoGenerated
	private Button botonModId;
	@AutoGenerated
	private Label valorId;
	@AutoGenerated
	private Label labelId;
	@AutoGenerated
	private Button botonEnvParteDenunciada;
	@AutoGenerated
	private Button botonModParteDenunciada;
	@AutoGenerated
	private TextField campoParteDenunciada;
	@AutoGenerated
	private Button botonEnvParteDenunciante;
	@AutoGenerated
	private TextField campoParteDenunciante;
	@AutoGenerated
	private Button botonModParteDenunciante;
	@AutoGenerated
	private Label valorParteDenunciante;
	@AutoGenerated
	private Label labelParteDenunciante;
	@AutoGenerated
	private Button botonEnvCarnet;
	@AutoGenerated
	private TextField campoCarnet;
	@AutoGenerated
	private Button botonModCarnet;
	@AutoGenerated
	private Label valorCarnet;
	@AutoGenerated
	private Label labelCarnet;
	@AutoGenerated
	private Label valorParteDenunciada;
	@AutoGenerated
	private Label labelParteDenunciada;
	@AutoGenerated
	private Button botonEnvFechaDenuncia;
	@AutoGenerated
	private TextField campoFechaDenuncia;
	@AutoGenerated
	private Button botonModFechaDenuncia;
	@AutoGenerated
	private Label valorFechaDenuncia;
	@AutoGenerated
	private Label labelFechaDenuncia;
	@AutoGenerated
	private AbsoluteLayout LayoutInfoGeneral;
	@AutoGenerated
	private Button botonEnvResponsable;
	@AutoGenerated
	private TextField campoResponsable;
	@AutoGenerated
	private Button botonModResponsable;
	@AutoGenerated
	private Label valorResponsable;
	@AutoGenerated
	private Label labelResponsable;
	@AutoGenerated
	private Button botonModEstado;
	@AutoGenerated
	private Label labelEstado;
	@AutoGenerated
	private Label valorEstado;
	@AutoGenerated
	private Button botonEnvEstado;
	@AutoGenerated
	private Button botonEnvClas;
	@AutoGenerated
	private TextField campoClas;
	@AutoGenerated
	private TextField campoEstado;
	@AutoGenerated
	private Button botonModClas;
	@AutoGenerated
	private Label valorClas;
	@AutoGenerated
	private Label labelClas;
	@AutoGenerated
	private Button botonRechazar;
	@AutoGenerated
	private Button botonAceptar;
	@AutoGenerated
	private Label labelConfirmacion;
	@AutoGenerated
	private Label valorNumExpediente;
	@AutoGenerated
	private Label valorInst;
	@AutoGenerated
	private Label labelInst;
	@AutoGenerated
	private Button botonVolver;
	@AutoGenerated
	private Button botonArchivar;
	@AutoGenerated
	private Button botonLog;
	@AutoGenerated
	private Label labelNumExpediente;
	private ControladorExpediente controlador;
	private Controlador control;
	private HashMap<String, String> datosExpediente;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public VistaExpediente() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		controlador = ControladorExpediente.obtenerInstancia();
		control = Controlador.obtenerInstancia();
		
		//Pedir los datos del expediente
		datosExpediente = controlador.obtenerDatos();
		
		//Ocultar los campos de modificación
		desaparecerCampos();
		
		//Inactivar la modificación del expediente si está archivado o si no se tiene permisos de modificación
		if (control.getTipoUsuario() != "Instructor" && control.getTipoUsuario() != "Asistente"){
			
			//desaparecerBotones();
		}
		else if (control.getNumInstructor() != datosExpediente.get("Instructor Asignado")) {
			
			//desaparecerBotones();
		}
		else if (datosExpediente.get("Archivado").compareTo("t") == 0) {
			
			desaparecerBotones();
		}
		
		valorNumExpediente.setValue(datosExpediente.get("Numero Expediente"));
		valorInst.setValue(datosExpediente.get("Instructor Asignado"));
		valorClas.setValue(datosExpediente.get("Clasificacion"));
		
		botonArchivar.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				botonAceptar.setVisible(true);
				botonRechazar.setVisible(true);
				labelConfirmacion.setVisible(true);
			}
			
		});
		
		botonAceptar.addClickListener(new ClickListener () {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				//controlador.enviarDatos("true", "archivado");
				control.cambiarVista("Expediente", datosExpediente.get("Codigo"));
			}
			
		});
		
		botonRechazar.addClickListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				botonAceptar.setVisible(false);
				botonRechazar.setVisible(false);
				labelConfirmacion.setVisible(false);
			}
			
		});
		
		botonLog.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				control.cambiarVista("Logs", datosExpediente.get("Codigo"));
			}
			
		});
	
		botonVolver.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				if (datosExpediente.get("Archivado") == "true") {
					//control.cambiarVista("Lista Expedientes Archivados");
				} else {
					control.cambiarVista("Lista Expedientes");
				}
			}
			
		});
		
		botonModEstado.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				desaparecerCampos();
				campoEstado.setVisible(true);
				botonEnvEstado.setVisible(true);
				
			}
			
		});
		
		botonEnvEstado.addClickListener(new ClickListener () {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				// if datos válidos
					//String nuevoDato = campoEstado.getValue();
					//controlador.enviarDatos(nuevoDato, "estado");
					//control.cambiarVista("Expediente", datosExpediente.get("Codigo"));
			}
			
		});
		
		botonModClas.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				desaparecerCampos();
				campoClas.setVisible(true);
				botonEnvClas.setVisible(true);
				
			}
			
		});
		
		botonEnvClas.addClickListener(new ClickListener () {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				// if datos válidos
					String datoViejo = labelClas.getValue();
					String nuevoDato = campoClas.getValue();
					controlador.enviarDatos(nuevoDato, "clasificacion", datosExpediente.get("Instructor Asignado"), datosExpediente.get("Numero Expediente"), datoViejo);
					control.cambiarVista("Expediente", datosExpediente.get("Codigo"));
			}
			
		});
		
		botonModResponsable.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				desaparecerCampos();
				campoResponsable.setVisible(true);
				botonEnvResponsable.setVisible(true);
				
			}
			
		});
		
		botonEnvResponsable.addClickListener(new ClickListener () {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				// if datos válidos
					String datoViejo = labelResponsable.getValue();
					String nuevoDato = campoResponsable.getValue();
					controlador.enviarDatos(nuevoDato, "clasificacion", datosExpediente.get("Instructor Asignado"), datosExpediente.get("Numero Expediente"), datoViejo);
					control.cambiarVista("Expediente", datosExpediente.get("Codigo"));
			}
			
		});
		
		botonModFechaDenuncia.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				desaparecerCampos();
				campoFechaDenuncia.setVisible(true);
				botonEnvFechaDenuncia.setVisible(true);
				
			}
			
		});
		
		botonEnvFechaDenuncia.addClickListener(new ClickListener () {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				// if datos válidos
					String datoViejo = labelFechaDenuncia.getValue();
					String nuevoDato = campoFechaDenuncia.getValue();
					controlador.enviarDatos(nuevoDato, "clasificacion", datosExpediente.get("Instructor Asignado"), datosExpediente.get("Numero Expediente"), datoViejo);
					control.cambiarVista("Expediente", datosExpediente.get("Codigo"));
			}
			
		});
		
		botonModParteDenunciada.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				desaparecerCampos();
				campoParteDenunciada.setVisible(true);
				botonEnvParteDenunciada.setVisible(true);
				
			}
			
		});
		
		botonEnvParteDenunciada.addClickListener(new ClickListener () {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				// if datos válidos
					String datoViejo = labelParteDenunciada.getValue();
					String nuevoDato = campoParteDenunciada.getValue();
					controlador.enviarDatos(nuevoDato, "clasificacion", datosExpediente.get("Instructor Asignado"), datosExpediente.get("Numero Expediente"), datoViejo);
					control.cambiarVista("Expediente", datosExpediente.get("Codigo"));
			}
			
		});
		
		botonModCarnet.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				desaparecerCampos();
				campoCarnet.setVisible(true);
				botonEnvCarnet.setVisible(true);
				
			}
			
		});
		
		botonEnvCarnet.addClickListener(new ClickListener () {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				// if datos válidos
					String datoViejo = labelCarnet.getValue();
					String nuevoDato = campoCarnet.getValue();
					controlador.enviarDatos(nuevoDato, "clasificacion", datosExpediente.get("Instructor Asignado"), datosExpediente.get("Numero Expediente"), datoViejo);
					control.cambiarVista("Expediente", datosExpediente.get("Codigo"));
			}
			
		});
		
		botonModParteDenunciante.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				desaparecerCampos();
				campoParteDenunciante.setVisible(true);
				botonEnvParteDenunciante.setVisible(true);
				
			}
			
		});
		
		botonEnvParteDenunciante.addClickListener(new ClickListener () {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				// if datos válidos
					String datoViejo = labelParteDenunciante.getValue();
					String nuevoDato = campoParteDenunciante.getValue();
					controlador.enviarDatos(nuevoDato, "clasificacion", datosExpediente.get("Instructor Asignado"), datosExpediente.get("Numero Expediente"), datoViejo);
					control.cambiarVista("Expediente", datosExpediente.get("Codigo"));
			}
			
		});
		
		botonModId.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				desaparecerCampos();
				campoId.setVisible(true);
				botonEnvId.setVisible(true);
				
			}
			
		});
		
		botonEnvId.addClickListener(new ClickListener () {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				// if datos válidos
					String datoViejo = labelId.getValue();
					String nuevoDato = campoId.getValue();
					controlador.enviarDatos(nuevoDato, "clasificacion", datosExpediente.get("Instructor Asignado"), datosExpediente.get("Numero Expediente"), datoViejo);
					control.cambiarVista("Expediente", datosExpediente.get("Codigo"));
			}
			
		});
		
		//Aqui va Causa
		
		botonModPlazo.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				desaparecerCampos();
				campoPlazo.setVisible(true);
				botonEnvPlazo.setVisible(true);
				
			}
			
		});
		
		botonEnvPlazo.addClickListener(new ClickListener () {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				// if datos válidos
					String datoViejo = labelPlazo.getValue();
					String nuevoDato = campoPlazo.getValue();
					controlador.enviarDatos(nuevoDato, "clasificacion", datosExpediente.get("Instructor Asignado"), datosExpediente.get("Numero Expediente"), datoViejo);
					control.cambiarVista("Expediente", datosExpediente.get("Codigo"));
			}
			
		});
		
		botonModTiempoTranscurrido.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				desaparecerCampos();
				campoTiempoTranscurrido.setVisible(true);
				botonEnvTiempoTranscurrido.setVisible(true);
				
			}
			
		});
		
		botonEnvTiempoTranscurrido.addClickListener(new ClickListener () {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				// if datos válidos
					String datoViejo = labelTiempoTranscurrido.getValue();
					String nuevoDato = campoTiempoTranscurrido.getValue();
					controlador.enviarDatos(nuevoDato, "clasificacion", datosExpediente.get("Instructor Asignado"), datosExpediente.get("Numero Expediente"), datoViejo);
					control.cambiarVista("Expediente", datosExpediente.get("Codigo"));
			}
			
		});
		
		botonModCondPlazo.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				desaparecerCampos();
				campoCondPlazo.setVisible(true);
				botonEnvCondPlazo.setVisible(true);
				
			}
			
		});
		
		botonEnvCondPlazo.addClickListener(new ClickListener () {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				// if datos válidos
					String datoViejo = labelCondPlazo.getValue();
					String nuevoDato = campoCondPlazo.getValue();
					controlador.enviarDatos(nuevoDato, "clasificacion", datosExpediente.get("Instructor Asignado"), datosExpediente.get("Numero Expediente"), datoViejo);
					control.cambiarVista("Expediente", datosExpediente.get("Codigo"));
			}
			
		});
		
		botonModUbicacion.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				desaparecerCampos();
				campoUbicacion.setVisible(true);
				botonEnvUbicacion.setVisible(true);
				
			}
			
		});
		
		//Aqui van otros campos
		
		botonEnvUbicacion.addClickListener(new ClickListener () {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				// if datos válidos
					String datoViejo = labelUbicacion.getValue();
					String nuevoDato = campoUbicacion.getValue();
					controlador.enviarDatos(nuevoDato, "clasificacion", datosExpediente.get("Instructor Asignado"), datosExpediente.get("Numero Expediente"), datoViejo);
					control.cambiarVista("Expediente", datosExpediente.get("Codigo"));
			}
			
		});
		
		botonModFechaIng.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				desaparecerCampos();
				campoFechaIng.setVisible(true);
				botonEnvFechaIng.setVisible(true);
				
			}
			
		});
		
		botonEnvFechaIng.addClickListener(new ClickListener () {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				// if datos válidos
					String datoViejo = labelFechaIng.getValue();
					String nuevoDato = campoFechaIng.getValue();
					controlador.enviarDatos(nuevoDato, "clasificacion", datosExpediente.get("Instructor Asignado"), datosExpediente.get("Numero Expediente"), datoViejo);
					control.cambiarVista("Expediente", datosExpediente.get("Codigo"));
			}
			
		});
		
		
		
		
		
		botonModFechaCambioEstado.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				desaparecerCampos();
				campoFechaCambioEstado.setVisible(true);
				botonEnvFechaCambioEstado.setVisible(true);
				
			}
			
		});
		
		botonEnvFechaCambioEstado.addClickListener(new ClickListener () {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				// if datos válidos
					String datoViejo = labelFechaCambioEstado.getValue();
					String nuevoDato = campoFechaCambioEstado.getValue();
					controlador.enviarDatos(nuevoDato, "clasificacion", datosExpediente.get("Instructor Asignado"), datosExpediente.get("Numero Expediente"), datoViejo);
					control.cambiarVista("Expediente", datosExpediente.get("Codigo"));
			}
			
		});
		
		
		
	}
	
	private void desaparecerCampos() {
		
		botonAceptar.setVisible(false);
		botonRechazar.setVisible(false);
		labelConfirmacion.setVisible(false);
		
		campoClas.setVisible(false);
		botonEnvClas.setVisible(false);
		campoEstado.setVisible(false);
		botonEnvEstado.setVisible(false);
		
	}
	
	private void desaparecerBotones() {
		
		botonModEstado.setVisible(false);
		botonModClas.setVisible(false);

		botonArchivar.setVisible(false);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// labelNumExpediente
		labelNumExpediente = new Label();
		labelNumExpediente.setStyleName("titulo");
		labelNumExpediente.setImmediate(false);
		labelNumExpediente.setWidth("-1px");
		labelNumExpediente.setHeight("-1px");
		labelNumExpediente.setValue("Expediente");
		mainLayout.addComponent(labelNumExpediente, "top:60.0px;left:60.0px;");
		
		// botonLog
		botonLog = new Button();
		botonLog.setCaption("Registro");
		botonLog.setImmediate(true);
		botonLog.setWidth("-1px");
		botonLog.setHeight("-1px");
		mainLayout.addComponent(botonLog, "top:60.0px;left:850.0px;");
		
		// botonArchivar
		botonArchivar = new Button();
		botonArchivar.setCaption("Archivar");
		botonArchivar.setImmediate(true);
		botonArchivar.setWidth("-1px");
		botonArchivar.setHeight("-1px");
		mainLayout.addComponent(botonArchivar, "top:60.0px;left:700.0px;");
		
		// botonVolver
		botonVolver = new Button();
		botonVolver.setCaption("Volver");
		botonVolver.setImmediate(true);
		botonVolver.setWidth("-1px");
		botonVolver.setHeight("-1px");
		mainLayout.addComponent(botonVolver, "top:60.0px;left:1000.0px;");
		
		// labelInst
		labelInst = new Label();
		labelInst.setImmediate(false);
		labelInst.setWidth("-1px");
		labelInst.setHeight("-1px");
		labelInst.setValue("Instructor Asignado:");
		mainLayout.addComponent(labelInst, "top:150.0px;left:60.0px;");
		
		// valorInst
		valorInst = new Label();
		valorInst.setImmediate(false);
		valorInst.setWidth("-1px");
		valorInst.setHeight("-1px");
		valorInst.setValue("Label");
		mainLayout.addComponent(valorInst, "top:150.0px;left:231.0px;");
		
		// valorNumExpediente
		valorNumExpediente = new Label();
		valorNumExpediente.setImmediate(false);
		valorNumExpediente.setWidth("-1px");
		valorNumExpediente.setHeight("-1px");
		valorNumExpediente.setValue("Label");
		mainLayout.addComponent(valorNumExpediente, "top:60.0px;left:160.0px;");
		
		// labelConfirmacion
		labelConfirmacion = new Label();
		labelConfirmacion.setImmediate(false);
		labelConfirmacion.setWidth("-1px");
		labelConfirmacion.setHeight("-1px");
		labelConfirmacion.setValue("¿Está seguro que desea archivar el expediente?");
		mainLayout.addComponent(labelConfirmacion, "top:150.0px;left:569.0px;");
		
		// botonAceptar
		botonAceptar = new Button();
		botonAceptar.setCaption("Sí");
		botonAceptar.setImmediate(true);
		botonAceptar.setWidth("-1px");
		botonAceptar.setHeight("-1px");
		mainLayout.addComponent(botonAceptar, "top:142.0px;left:950.0px;");
		
		// botonRechazar
		botonRechazar = new Button();
		botonRechazar.setCaption("No");
		botonRechazar.setImmediate(true);
		botonRechazar.setWidth("-1px");
		botonRechazar.setHeight("-1px");
		mainLayout.addComponent(botonRechazar, "top:142.0px;left:1020.0px;");
		
		// Acordeon
		Acordeon = buildAcordeon();
		mainLayout.addComponent(Acordeon, "top:240.0px;left:60.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private Accordion buildAcordeon() {
		// common part: create layout
		Acordeon = new Accordion();
		Acordeon.setImmediate(true);
		Acordeon.setWidth("90.0%");
		Acordeon.setHeight("90.0%");
		
		// LayoutInfoGeneral
		LayoutInfoGeneral = buildLayoutInfoGeneral();
		Acordeon.addTab(LayoutInfoGeneral, "Información General", null);
		
		// LayoutInfoDenuncia
		LayoutInfoDenuncia = buildLayoutInfoDenuncia();
		Acordeon.addTab(LayoutInfoDenuncia, "Información de la Denuncia", null);
		
		// LayoutPlazo
		LayoutPlazo = buildLayoutPlazo();
		Acordeon.addTab(LayoutPlazo, "Plazo", null);
		
		// LayoutUbicacion
		LayoutUbicacion = buildLayoutUbicacion();
		Acordeon.addTab(LayoutUbicacion, "Ubicación", null);
		
		// LayoutFechas
		LayoutFechas = buildLayoutFechas();
		Acordeon.addTab(LayoutFechas, "Fechas", null);
		
		return Acordeon;
	}

	@AutoGenerated
	private AbsoluteLayout buildLayoutInfoGeneral() {
		// common part: create layout
		LayoutInfoGeneral = new AbsoluteLayout();
		LayoutInfoGeneral.setImmediate(false);
		LayoutInfoGeneral.setWidth("100.0%");
		LayoutInfoGeneral.setHeight("100.0%");
		
		// labelClas
		labelClas = new Label();
		labelClas.setImmediate(false);
		labelClas.setWidth("-1px");
		labelClas.setHeight("-1px");
		labelClas.setValue("Clasificación:");
		LayoutInfoGeneral.addComponent(labelClas, "top:0.0px;left:350.0px;");
		
		// valorClas
		valorClas = new Label();
		valorClas.setImmediate(false);
		valorClas.setWidth("-1px");
		valorClas.setHeight("-1px");
		valorClas.setValue("Label");
		LayoutInfoGeneral.addComponent(valorClas, "top:40.0px;left:350.0px;");
		
		// botonModClas
		botonModClas = new Button();
		botonModClas.setCaption("Modificar");
		botonModClas.setImmediate(true);
		botonModClas.setWidth("-1px");
		botonModClas.setHeight("-1px");
		LayoutInfoGeneral.addComponent(botonModClas, "top:80.0px;left:350.0px;");
		
		// campoEstado
		campoEstado = new TextField();
		campoEstado.setImmediate(false);
		campoEstado.setWidth("-1px");
		campoEstado.setHeight("-1px");
		LayoutInfoGeneral.addComponent(campoEstado, "top:130.0px;left:0.0px;");
		
		// campoClas
		campoClas = new TextField();
		campoClas.setImmediate(false);
		campoClas.setWidth("-1px");
		campoClas.setHeight("-1px");
		LayoutInfoGeneral.addComponent(campoClas, "top:130.0px;left:350.0px;");
		
		// botonEnvClas
		botonEnvClas = new Button();
		botonEnvClas.setCaption("M");
		botonEnvClas.setImmediate(true);
		botonEnvClas.setWidth("-1px");
		botonEnvClas.setHeight("-1px");
		LayoutInfoGeneral.addComponent(botonEnvClas, "top:130.0px;left:550.0px;");
		
		// botonEnvEstado
		botonEnvEstado = new Button();
		botonEnvEstado.setCaption("M");
		botonEnvEstado.setImmediate(true);
		botonEnvEstado.setWidth("-1px");
		botonEnvEstado.setHeight("-1px");
		LayoutInfoGeneral.addComponent(botonEnvEstado, "top:130.0px;left:200.0px;");
		
		// valorEstado
		valorEstado = new Label();
		valorEstado.setImmediate(false);
		valorEstado.setWidth("-1px");
		valorEstado.setHeight("-1px");
		valorEstado.setValue("Label");
		LayoutInfoGeneral.addComponent(valorEstado, "top:40.0px;left:0.0px;");
		
		// labelEstado
		labelEstado = new Label();
		labelEstado.setImmediate(false);
		labelEstado.setWidth("-1px");
		labelEstado.setHeight("-1px");
		labelEstado.setValue("Estado: ");
		LayoutInfoGeneral.addComponent(labelEstado, "top:0.0px;left:0.0px;");
		
		// botonModEstado
		botonModEstado = new Button();
		botonModEstado.setCaption("Modificar");
		botonModEstado.setImmediate(true);
		botonModEstado.setWidth("-1px");
		botonModEstado.setHeight("-1px");
		LayoutInfoGeneral.addComponent(botonModEstado, "top:80.0px;left:0.0px;");
		
		// labelResponsable
		labelResponsable = new Label();
		labelResponsable.setImmediate(false);
		labelResponsable.setWidth("-1px");
		labelResponsable.setHeight("-1px");
		labelResponsable.setValue("Responsable:");
		LayoutInfoGeneral.addComponent(labelResponsable, "top:0.0px;left:700.0px;");
		
		// valorResponsable
		valorResponsable = new Label();
		valorResponsable.setImmediate(false);
		valorResponsable.setWidth("-1px");
		valorResponsable.setHeight("-1px");
		valorResponsable.setValue("Label");
		LayoutInfoGeneral.addComponent(valorResponsable, "top:40.0px;left:700.0px;");
		
		// botonModResponsable
		botonModResponsable = new Button();
		botonModResponsable.setCaption("Modificar");
		botonModResponsable.setImmediate(true);
		botonModResponsable.setWidth("-1px");
		botonModResponsable.setHeight("-1px");
		LayoutInfoGeneral.addComponent(botonModResponsable, "top:80.0px;left:700.0px;");
		
		// campoResponsable
		campoResponsable = new TextField();
		campoResponsable.setImmediate(false);
		campoResponsable.setWidth("-1px");
		campoResponsable.setHeight("-1px");
		LayoutInfoGeneral.addComponent(campoResponsable, "top:130.0px;left:700.0px;");
		
		// botonEnvResponsable
		botonEnvResponsable = new Button();
		botonEnvResponsable.setCaption("M");
		botonEnvResponsable.setImmediate(true);
		botonEnvResponsable.setWidth("-1px");
		botonEnvResponsable.setHeight("-1px");
		LayoutInfoGeneral.addComponent(botonEnvResponsable, "top:130.0px;left:900.0px;");
		
		return LayoutInfoGeneral;
	}

	@AutoGenerated
	private AbsoluteLayout buildLayoutInfoDenuncia() {
		// common part: create layout
		LayoutInfoDenuncia = new AbsoluteLayout();
		LayoutInfoDenuncia.setImmediate(false);
		LayoutInfoDenuncia.setWidth("100.0%");
		LayoutInfoDenuncia.setHeight("100.0%");
		
		// labelFechaDenuncia
		labelFechaDenuncia = new Label();
		labelFechaDenuncia.setImmediate(false);
		labelFechaDenuncia.setWidth("-1px");
		labelFechaDenuncia.setHeight("-1px");
		labelFechaDenuncia.setValue("Fecha Denuncia:");
		LayoutInfoDenuncia.addComponent(labelFechaDenuncia, "top:0.0px;left:0.0px;");
		
		// valorFechaDenuncia
		valorFechaDenuncia = new Label();
		valorFechaDenuncia.setImmediate(false);
		valorFechaDenuncia.setWidth("-1px");
		valorFechaDenuncia.setHeight("-1px");
		valorFechaDenuncia.setValue("Label");
		LayoutInfoDenuncia.addComponent(valorFechaDenuncia, "top:40.0px;left:0.0px;");
		
		// botonModFechaDenuncia
		botonModFechaDenuncia = new Button();
		botonModFechaDenuncia.setCaption("Modificar");
		botonModFechaDenuncia.setImmediate(true);
		botonModFechaDenuncia.setWidth("-1px");
		botonModFechaDenuncia.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(botonModFechaDenuncia, "top:80.0px;left:0.0px;");
		
		// campoFechaDenuncia
		campoFechaDenuncia = new TextField();
		campoFechaDenuncia.setImmediate(false);
		campoFechaDenuncia.setWidth("-1px");
		campoFechaDenuncia.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoFechaDenuncia, "top:130.0px;left:0.0px;");
		
		// botonEnvFechaDenuncia
		botonEnvFechaDenuncia = new Button();
		botonEnvFechaDenuncia.setCaption("M");
		botonEnvFechaDenuncia.setImmediate(true);
		botonEnvFechaDenuncia.setWidth("-1px");
		botonEnvFechaDenuncia.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(botonEnvFechaDenuncia, "top:130.0px;left:200.0px;");
		
		// labelParteDenunciada
		labelParteDenunciada = new Label();
		labelParteDenunciada.setImmediate(false);
		labelParteDenunciada.setWidth("-1px");
		labelParteDenunciada.setHeight("-1px");
		labelParteDenunciada.setValue("Parte Denunciada:");
		LayoutInfoDenuncia.addComponent(labelParteDenunciada, "top:0.0px;left:350.0px;");
		
		// valorParteDenunciada
		valorParteDenunciada = new Label();
		valorParteDenunciada.setImmediate(false);
		valorParteDenunciada.setWidth("-1px");
		valorParteDenunciada.setHeight("-1px");
		valorParteDenunciada.setValue("Label");
		LayoutInfoDenuncia.addComponent(valorParteDenunciada, "top:40.0px;left:350.0px;");
		
		// labelCarnet
		labelCarnet = new Label();
		labelCarnet.setImmediate(false);
		labelCarnet.setWidth("-1px");
		labelCarnet.setHeight("-1px");
		labelCarnet.setValue("Carnet:");
		LayoutInfoDenuncia.addComponent(labelCarnet, "top:0.0px;left:700.0px;");
		
		// valorCarnet
		valorCarnet = new Label();
		valorCarnet.setImmediate(false);
		valorCarnet.setWidth("-1px");
		valorCarnet.setHeight("-1px");
		valorCarnet.setValue("Label");
		LayoutInfoDenuncia.addComponent(valorCarnet, "top:40.0px;left:700.0px;");
		
		// botonModCarnet
		botonModCarnet = new Button();
		botonModCarnet.setCaption("Modificar");
		botonModCarnet.setImmediate(true);
		botonModCarnet.setWidth("-1px");
		botonModCarnet.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(botonModCarnet, "top:80.0px;left:700.0px;");
		
		// campoCarnet
		campoCarnet = new TextField();
		campoCarnet.setImmediate(false);
		campoCarnet.setWidth("-1px");
		campoCarnet.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoCarnet, "top:130.0px;left:700.0px;");
		
		// botonEnvCarnet
		botonEnvCarnet = new Button();
		botonEnvCarnet.setCaption("M");
		botonEnvCarnet.setImmediate(true);
		botonEnvCarnet.setWidth("-1px");
		botonEnvCarnet.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(botonEnvCarnet, "top:130.0px;left:900.0px;");
		
		// labelParteDenunciante
		labelParteDenunciante = new Label();
		labelParteDenunciante.setImmediate(false);
		labelParteDenunciante.setWidth("-1px");
		labelParteDenunciante.setHeight("-1px");
		labelParteDenunciante.setValue("Parte Denunciante:");
		LayoutInfoDenuncia.addComponent(labelParteDenunciante, "top:200.0px;left:0.0px;");
		
		// valorParteDenunciante
		valorParteDenunciante = new Label();
		valorParteDenunciante.setImmediate(false);
		valorParteDenunciante.setWidth("-1px");
		valorParteDenunciante.setHeight("-1px");
		valorParteDenunciante.setValue("Label");
		LayoutInfoDenuncia.addComponent(valorParteDenunciante, "top:240.0px;left:0.0px;");
		
		// botonModParteDenunciante
		botonModParteDenunciante = new Button();
		botonModParteDenunciante.setCaption("Modificar");
		botonModParteDenunciante.setImmediate(true);
		botonModParteDenunciante.setWidth("-1px");
		botonModParteDenunciante.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(botonModParteDenunciante, "top:280.0px;left:0.0px;");
		
		// campoParteDenunciante
		campoParteDenunciante = new TextField();
		campoParteDenunciante.setImmediate(false);
		campoParteDenunciante.setWidth("-1px");
		campoParteDenunciante.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoParteDenunciante, "top:330.0px;left:0.0px;");
		
		// botonEnvParteDenunciante
		botonEnvParteDenunciante = new Button();
		botonEnvParteDenunciante.setCaption("M");
		botonEnvParteDenunciante.setImmediate(true);
		botonEnvParteDenunciante.setWidth("-1px");
		botonEnvParteDenunciante.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(botonEnvParteDenunciante, "top:330.0px;left:200.0px;");
		
		// campoParteDenunciada
		campoParteDenunciada = new TextField();
		campoParteDenunciada.setImmediate(false);
		campoParteDenunciada.setWidth("-1px");
		campoParteDenunciada.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoParteDenunciada, "top:130.0px;left:350.0px;");
		
		// botonModParteDenunciada
		botonModParteDenunciada = new Button();
		botonModParteDenunciada.setCaption("Modificar");
		botonModParteDenunciada.setImmediate(true);
		botonModParteDenunciada.setWidth("-1px");
		botonModParteDenunciada.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(botonModParteDenunciada, "top:80.0px;left:350.0px;");
		
		// botonEnvParteDenunciada
		botonEnvParteDenunciada = new Button();
		botonEnvParteDenunciada.setCaption("M");
		botonEnvParteDenunciada.setImmediate(true);
		botonEnvParteDenunciada.setWidth("-1px");
		botonEnvParteDenunciada.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(botonEnvParteDenunciada, "top:130.0px;left:550.0px;");
		
		// labelId
		labelId = new Label();
		labelId.setImmediate(false);
		labelId.setWidth("-1px");
		labelId.setHeight("-1px");
		labelId.setValue("Identificación:");
		LayoutInfoDenuncia.addComponent(labelId, "top:200.0px;left:350.0px;");
		
		// valorId
		valorId = new Label();
		valorId.setImmediate(false);
		valorId.setWidth("-1px");
		valorId.setHeight("-1px");
		valorId.setValue("Label");
		LayoutInfoDenuncia.addComponent(valorId, "top:240.0px;left:350.0px;");
		
		// botonModId
		botonModId = new Button();
		botonModId.setCaption("Modificar");
		botonModId.setImmediate(true);
		botonModId.setWidth("-1px");
		botonModId.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(botonModId, "top:280.0px;left:350.0px;");
		
		// campoId
		campoId = new TextField();
		campoId.setImmediate(false);
		campoId.setWidth("-1px");
		campoId.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoId, "top:330.0px;left:350.0px;");
		
		// botonEnvId
		botonEnvId = new Button();
		botonEnvId.setCaption("M");
		botonEnvId.setImmediate(true);
		botonEnvId.setWidth("-1px");
		botonEnvId.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(botonEnvId, "top:330.0px;left:550.0px;");
		
		// labelCausa
		labelCausa = new Label();
		labelCausa.setImmediate(false);
		labelCausa.setWidth("-1px");
		labelCausa.setHeight("-1px");
		labelCausa.setValue("Causa:");
		LayoutInfoDenuncia.addComponent(labelCausa, "top:200.0px;left:700.0px;");
		
		// valorCausa
		valorCausa = new Label();
		valorCausa.setImmediate(false);
		valorCausa.setWidth("-1px");
		valorCausa.setHeight("-1px");
		valorCausa.setValue("Label");
		LayoutInfoDenuncia.addComponent(valorCausa, "top:240.0px;left:700.0px;");
		
		// campoCausa
		campoCausa = new TextField();
		campoCausa.setImmediate(false);
		campoCausa.setWidth("-1px");
		campoCausa.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoCausa, "top:330.0px;left:700.0px;");
		
		// botonModCausa
		botonModCausa = new Button();
		botonModCausa.setCaption("Modificar");
		botonModCausa.setImmediate(true);
		botonModCausa.setWidth("-1px");
		botonModCausa.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(botonModCausa, "top:280.0px;left:700.0px;");
		
		// botonEnvCausa
		botonEnvCausa = new Button();
		botonEnvCausa.setCaption("M");
		botonEnvCausa.setImmediate(true);
		botonEnvCausa.setWidth("-1px");
		botonEnvCausa.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(botonEnvCausa, "top:330.0px;left:900.0px;");
		
		// labelArtAplicables
		labelArtAplicables = new Label();
		labelArtAplicables.setImmediate(false);
		labelArtAplicables.setWidth("-1px");
		labelArtAplicables.setHeight("-1px");
		labelArtAplicables.setValue("Artículos Aplicables:");
		LayoutInfoDenuncia.addComponent(labelArtAplicables, "top:400.0px;left:0.0px;");
		
		// valorArtAplicables
		valorArtAplicables = new Label();
		valorArtAplicables.setImmediate(false);
		valorArtAplicables.setWidth("-1px");
		valorArtAplicables.setHeight("-1px");
		valorArtAplicables.setValue("Label");
		LayoutInfoDenuncia.addComponent(valorArtAplicables, "top:440.0px;left:0.0px;");
		
		// botonModArtAplicables
		botonModArtAplicables = new Button();
		botonModArtAplicables.setCaption("Modificar");
		botonModArtAplicables.setImmediate(true);
		botonModArtAplicables.setWidth("-1px");
		botonModArtAplicables.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(botonModArtAplicables, "top:480.0px;left:0.0px;");
		
		// campoArtAplicables
		campoArtAplicables = new TextField();
		campoArtAplicables.setImmediate(false);
		campoArtAplicables.setWidth("-1px");
		campoArtAplicables.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoArtAplicables, "top:530.0px;left:0.0px;");
		
		// botonEnvArtAplicables
		botonEnvArtAplicables = new Button();
		botonEnvArtAplicables.setCaption("M");
		botonEnvArtAplicables.setImmediate(true);
		botonEnvArtAplicables.setWidth("-1px");
		botonEnvArtAplicables.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(botonEnvArtAplicables, "top:530.0px;left:200.0px;");
		
		// labelFechaAudiencia
		labelFechaAudiencia = new Label();
		labelFechaAudiencia.setImmediate(false);
		labelFechaAudiencia.setWidth("-1px");
		labelFechaAudiencia.setHeight("-1px");
		labelFechaAudiencia.setValue("Fecha Audiencia:");
		LayoutInfoDenuncia.addComponent(labelFechaAudiencia, "top:400.0px;left:350.0px;");
		
		// valorFechaAudiencia
		valorFechaAudiencia = new Label();
		valorFechaAudiencia.setImmediate(false);
		valorFechaAudiencia.setWidth("-1px");
		valorFechaAudiencia.setHeight("-1px");
		valorFechaAudiencia.setValue("Label");
		LayoutInfoDenuncia.addComponent(valorFechaAudiencia, "top:440.0px;left:350.0px;");
		
		// botonModFechaAudiencia
		botonModFechaAudiencia = new Button();
		botonModFechaAudiencia.setCaption("Modificar");
		botonModFechaAudiencia.setImmediate(true);
		botonModFechaAudiencia.setWidth("-1px");
		botonModFechaAudiencia.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(botonModFechaAudiencia, "top:480.0px;left:350.0px;");
		
		// campoFechaAudiencia
		campoFechaAudiencia = new TextField();
		campoFechaAudiencia.setImmediate(false);
		campoFechaAudiencia.setWidth("-1px");
		campoFechaAudiencia.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoFechaAudiencia, "top:530.0px;left:350.0px;");
		
		// botonEnvFechaAudiencia
		botonEnvFechaAudiencia = new Button();
		botonEnvFechaAudiencia.setCaption("M");
		botonEnvFechaAudiencia.setImmediate(true);
		botonEnvFechaAudiencia.setWidth("-1px");
		botonEnvFechaAudiencia.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(botonEnvFechaAudiencia, "top:530.0px;left:550.0px;");
		
		// labelHoraAudiencia
		labelHoraAudiencia = new Label();
		labelHoraAudiencia.setImmediate(false);
		labelHoraAudiencia.setWidth("-1px");
		labelHoraAudiencia.setHeight("-1px");
		labelHoraAudiencia.setValue("Hora Audiencia:");
		LayoutInfoDenuncia.addComponent(labelHoraAudiencia, "top:400.0px;left:700.0px;");
		
		// valorHoraAudiencia
		valorHoraAudiencia = new Label();
		valorHoraAudiencia.setImmediate(false);
		valorHoraAudiencia.setWidth("-1px");
		valorHoraAudiencia.setHeight("-1px");
		valorHoraAudiencia.setValue("Label");
		LayoutInfoDenuncia.addComponent(valorHoraAudiencia, "top:440.0px;left:700.0px;");
		
		// botonModHoraAudiencia
		botonModHoraAudiencia = new Button();
		botonModHoraAudiencia.setCaption("Modificar");
		botonModHoraAudiencia.setImmediate(true);
		botonModHoraAudiencia.setWidth("-1px");
		botonModHoraAudiencia.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(botonModHoraAudiencia, "top:480.0px;left:700.0px;");
		
		// campoHoraAudiencia
		campoHoraAudiencia = new TextField();
		campoHoraAudiencia.setImmediate(false);
		campoHoraAudiencia.setWidth("-1px");
		campoHoraAudiencia.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoHoraAudiencia, "top:530.0px;left:700.0px;");
		
		// botonEnvHoraAudiencia
		botonEnvHoraAudiencia = new Button();
		botonEnvHoraAudiencia.setCaption("M");
		botonEnvHoraAudiencia.setImmediate(true);
		botonEnvHoraAudiencia.setWidth("-1px");
		botonEnvHoraAudiencia.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(botonEnvHoraAudiencia, "top:530.0px;left:900.0px;");
		
		return LayoutInfoDenuncia;
	}

	@AutoGenerated
	private AbsoluteLayout buildLayoutPlazo() {
		// common part: create layout
		LayoutPlazo = new AbsoluteLayout();
		LayoutPlazo.setImmediate(false);
		LayoutPlazo.setWidth("100.0%");
		LayoutPlazo.setHeight("100.0%");
		
		// labelPlazo
		labelPlazo = new Label();
		labelPlazo.setImmediate(false);
		labelPlazo.setWidth("-1px");
		labelPlazo.setHeight("-1px");
		labelPlazo.setValue("Plazo Meta:");
		LayoutPlazo.addComponent(labelPlazo, "top:0.0px;left:0.0px;");
		
		// valorPlazo
		valorPlazo = new Label();
		valorPlazo.setImmediate(false);
		valorPlazo.setWidth("-1px");
		valorPlazo.setHeight("-1px");
		valorPlazo.setValue("Label");
		LayoutPlazo.addComponent(valorPlazo, "top:40.0px;left:0.0px;");
		
		// botonModPlazo
		botonModPlazo = new Button();
		botonModPlazo.setCaption("Modificar");
		botonModPlazo.setImmediate(true);
		botonModPlazo.setWidth("-1px");
		botonModPlazo.setHeight("-1px");
		LayoutPlazo.addComponent(botonModPlazo, "top:80.0px;left:0.0px;");
		
		// campoPlazo
		campoPlazo = new TextField();
		campoPlazo.setImmediate(false);
		campoPlazo.setWidth("-1px");
		campoPlazo.setHeight("-1px");
		LayoutPlazo.addComponent(campoPlazo, "top:130.0px;left:0.0px;");
		
		// botonEnvPlazo
		botonEnvPlazo = new Button();
		botonEnvPlazo.setCaption("M");
		botonEnvPlazo.setImmediate(true);
		botonEnvPlazo.setWidth("-1px");
		botonEnvPlazo.setHeight("-1px");
		LayoutPlazo.addComponent(botonEnvPlazo, "top:130.0px;left:200.0px;");
		
		// labelTiempoTranscurrido
		labelTiempoTranscurrido = new Label();
		labelTiempoTranscurrido.setImmediate(false);
		labelTiempoTranscurrido.setWidth("-1px");
		labelTiempoTranscurrido.setHeight("-1px");
		labelTiempoTranscurrido.setValue("Tiempo Transcurrido:");
		LayoutPlazo.addComponent(labelTiempoTranscurrido, "top:0.0px;left:350.0px;");
		
		// valorTiempoTranscurrido
		valorTiempoTranscurrido = new Label();
		valorTiempoTranscurrido.setImmediate(false);
		valorTiempoTranscurrido.setWidth("-1px");
		valorTiempoTranscurrido.setHeight("-1px");
		valorTiempoTranscurrido.setValue("Label");
		LayoutPlazo.addComponent(valorTiempoTranscurrido, "top:40.0px;left:350.0px;");
		
		// botonModTiempoTranscurrido
		botonModTiempoTranscurrido = new Button();
		botonModTiempoTranscurrido.setCaption("Modificar");
		botonModTiempoTranscurrido.setImmediate(true);
		botonModTiempoTranscurrido.setWidth("-1px");
		botonModTiempoTranscurrido.setHeight("-1px");
		LayoutPlazo.addComponent(botonModTiempoTranscurrido, "top:80.0px;left:350.0px;");
		
		// campoTiempoTranscurrido
		campoTiempoTranscurrido = new TextField();
		campoTiempoTranscurrido.setImmediate(false);
		campoTiempoTranscurrido.setWidth("-1px");
		campoTiempoTranscurrido.setHeight("-1px");
		LayoutPlazo.addComponent(campoTiempoTranscurrido, "top:130.0px;left:350.0px;");
		
		// botonEnvTiempoTranscurrido
		botonEnvTiempoTranscurrido = new Button();
		botonEnvTiempoTranscurrido.setCaption("M");
		botonEnvTiempoTranscurrido.setImmediate(true);
		botonEnvTiempoTranscurrido.setWidth("-1px");
		botonEnvTiempoTranscurrido.setHeight("-1px");
		LayoutPlazo.addComponent(botonEnvTiempoTranscurrido, "top:130.0px;left:550.0px;");
		
		// labelCondPlazo
		labelCondPlazo = new Label();
		labelCondPlazo.setImmediate(false);
		labelCondPlazo.setWidth("-1px");
		labelCondPlazo.setHeight("-1px");
		labelCondPlazo.setValue("Condición Plazo:");
		LayoutPlazo.addComponent(labelCondPlazo, "top:0.0px;left:700.0px;");
		
		// valorCondPlazo
		valorCondPlazo = new Label();
		valorCondPlazo.setImmediate(false);
		valorCondPlazo.setWidth("-1px");
		valorCondPlazo.setHeight("-1px");
		valorCondPlazo.setValue("Label");
		LayoutPlazo.addComponent(valorCondPlazo, "top:40.0px;left:700.0px;");
		
		// botonModCondPlazo
		botonModCondPlazo = new Button();
		botonModCondPlazo.setCaption("Modificar");
		botonModCondPlazo.setImmediate(true);
		botonModCondPlazo.setWidth("-1px");
		botonModCondPlazo.setHeight("-1px");
		LayoutPlazo.addComponent(botonModCondPlazo, "top:80.0px;left:700.0px;");
		
		// campoCondPlazo
		campoCondPlazo = new TextField();
		campoCondPlazo.setImmediate(false);
		campoCondPlazo.setWidth("-1px");
		campoCondPlazo.setHeight("-1px");
		LayoutPlazo.addComponent(campoCondPlazo, "top:130.0px;left:700.0px;");
		
		// botonEnvCondPlazo
		botonEnvCondPlazo = new Button();
		botonEnvCondPlazo.setCaption("M");
		botonEnvCondPlazo.setImmediate(true);
		botonEnvCondPlazo.setWidth("-1px");
		botonEnvCondPlazo.setHeight("-1px");
		LayoutPlazo.addComponent(botonEnvCondPlazo, "top:130.0px;left:900.0px;");
		
		return LayoutPlazo;
	}

	@AutoGenerated
	private AbsoluteLayout buildLayoutUbicacion() {
		// common part: create layout
		LayoutUbicacion = new AbsoluteLayout();
		LayoutUbicacion.setImmediate(false);
		LayoutUbicacion.setWidth("100.0%");
		LayoutUbicacion.setHeight("100.0%");
		
		// labelUbicacion
		labelUbicacion = new Label();
		labelUbicacion.setImmediate(false);
		labelUbicacion.setWidth("-1px");
		labelUbicacion.setHeight("-1px");
		labelUbicacion.setValue("Ubicación:");
		LayoutUbicacion.addComponent(labelUbicacion, "top:0.0px;left:0.0px;");
		
		// valorUbicacion
		valorUbicacion = new Label();
		valorUbicacion.setImmediate(false);
		valorUbicacion.setWidth("-1px");
		valorUbicacion.setHeight("-1px");
		valorUbicacion.setValue("Label");
		LayoutUbicacion.addComponent(valorUbicacion, "top:40.0px;left:0.0px;");
		
		// botonModUbicacion
		botonModUbicacion = new Button();
		botonModUbicacion.setCaption("Modificar");
		botonModUbicacion.setImmediate(true);
		botonModUbicacion.setWidth("-1px");
		botonModUbicacion.setHeight("-1px");
		LayoutUbicacion.addComponent(botonModUbicacion, "top:80.0px;left:0.0px;");
		
		// campoUbicacion
		campoUbicacion = new TextField();
		campoUbicacion.setImmediate(false);
		campoUbicacion.setWidth("-1px");
		campoUbicacion.setHeight("-1px");
		LayoutUbicacion.addComponent(campoUbicacion, "top:130.0px;left:0.0px;");
		
		// botonEnvUbicacion
		botonEnvUbicacion = new Button();
		botonEnvUbicacion.setCaption("M");
		botonEnvUbicacion.setImmediate(true);
		botonEnvUbicacion.setWidth("-1px");
		botonEnvUbicacion.setHeight("-1px");
		LayoutUbicacion.addComponent(botonEnvUbicacion, "top:130.0px;left:200.0px;");
		
		// labelMuebleUbicacion
		labelMuebleUbicacion = new Label();
		labelMuebleUbicacion.setImmediate(false);
		labelMuebleUbicacion.setWidth("-1px");
		labelMuebleUbicacion.setHeight("-1px");
		labelMuebleUbicacion.setValue("Mueble Ubicación:");
		LayoutUbicacion.addComponent(labelMuebleUbicacion, "top:0.0px;left:350.0px;");
		
		// valorMuebleUbicacion
		valorMuebleUbicacion = new Label();
		valorMuebleUbicacion.setImmediate(false);
		valorMuebleUbicacion.setWidth("-1px");
		valorMuebleUbicacion.setHeight("-1px");
		valorMuebleUbicacion.setValue("Label");
		LayoutUbicacion.addComponent(valorMuebleUbicacion, "top:40.0px;left:350.0px;");
		
		// botonModMuebleUbicacion
		botonModMuebleUbicacion = new Button();
		botonModMuebleUbicacion.setCaption("Modificar");
		botonModMuebleUbicacion.setImmediate(true);
		botonModMuebleUbicacion.setWidth("-1px");
		botonModMuebleUbicacion.setHeight("-1px");
		LayoutUbicacion.addComponent(botonModMuebleUbicacion, "top:80.0px;left:350.0px;");
		
		// campoMuebleUbicacion
		campoMuebleUbicacion = new TextField();
		campoMuebleUbicacion.setImmediate(false);
		campoMuebleUbicacion.setWidth("-1px");
		campoMuebleUbicacion.setHeight("-1px");
		LayoutUbicacion.addComponent(campoMuebleUbicacion, "top:130.0px;left:350.0px;");
		
		// botonEnvMuebleUbicacion
		botonEnvMuebleUbicacion = new Button();
		botonEnvMuebleUbicacion.setCaption("M");
		botonEnvMuebleUbicacion.setImmediate(true);
		botonEnvMuebleUbicacion.setWidth("-1px");
		botonEnvMuebleUbicacion.setHeight("-1px");
		LayoutUbicacion.addComponent(botonEnvMuebleUbicacion, "top:130.0px;left:550.0px;");
		
		// labelUbicLegajos
		labelUbicLegajos = new Label();
		labelUbicLegajos.setImmediate(false);
		labelUbicLegajos.setWidth("-1px");
		labelUbicLegajos.setHeight("-1px");
		labelUbicLegajos.setValue("Ubicación Legajos:");
		LayoutUbicacion.addComponent(labelUbicLegajos, "top:0.0px;left:700.0px;");
		
		// valorUbicLegajos
		valorUbicLegajos = new Label();
		valorUbicLegajos.setImmediate(false);
		valorUbicLegajos.setWidth("-1px");
		valorUbicLegajos.setHeight("-1px");
		valorUbicLegajos.setValue("Label");
		LayoutUbicacion.addComponent(valorUbicLegajos, "top:40.0px;left:700.0px;");
		
		// botonModUbicLegajos
		botonModUbicLegajos = new Button();
		botonModUbicLegajos.setCaption("Modificar");
		botonModUbicLegajos.setImmediate(true);
		botonModUbicLegajos.setWidth("-1px");
		botonModUbicLegajos.setHeight("-1px");
		LayoutUbicacion.addComponent(botonModUbicLegajos, "top:80.0px;left:700.0px;");
		
		// campoUbicLegajos
		campoUbicLegajos = new TextField();
		campoUbicLegajos.setImmediate(false);
		campoUbicLegajos.setWidth("-1px");
		campoUbicLegajos.setHeight("-1px");
		LayoutUbicacion.addComponent(campoUbicLegajos, "top:130.0px;left:700.0px;");
		
		// botonEnvUbicLegajos
		botonEnvUbicLegajos = new Button();
		botonEnvUbicLegajos.setCaption("M");
		botonEnvUbicLegajos.setImmediate(true);
		botonEnvUbicLegajos.setWidth("-1px");
		botonEnvUbicLegajos.setHeight("-1px");
		LayoutUbicacion.addComponent(botonEnvUbicLegajos, "top:130.0px;left:900.0px;");
		
		// labelCantLegajos
		labelCantLegajos = new Label();
		labelCantLegajos.setImmediate(false);
		labelCantLegajos.setWidth("-1px");
		labelCantLegajos.setHeight("-1px");
		labelCantLegajos.setValue("Cantidad de Legajos:");
		LayoutUbicacion.addComponent(labelCantLegajos, "top:200.0px;left:0.0px;");
		
		// valorCantLegajos
		valorCantLegajos = new Label();
		valorCantLegajos.setImmediate(false);
		valorCantLegajos.setWidth("-1px");
		valorCantLegajos.setHeight("-1px");
		valorCantLegajos.setValue("Label");
		LayoutUbicacion.addComponent(valorCantLegajos, "top:240.0px;left:0.0px;");
		
		// botonModCantLegajos
		botonModCantLegajos = new Button();
		botonModCantLegajos.setCaption("Modificar");
		botonModCantLegajos.setImmediate(true);
		botonModCantLegajos.setWidth("-1px");
		botonModCantLegajos.setHeight("-1px");
		LayoutUbicacion.addComponent(botonModCantLegajos, "top:280.0px;left:0.0px;");
		
		// campoCantLegajos
		campoCantLegajos = new TextField();
		campoCantLegajos.setImmediate(false);
		campoCantLegajos.setWidth("-1px");
		campoCantLegajos.setHeight("-1px");
		LayoutUbicacion.addComponent(campoCantLegajos, "top:330.0px;left:0.0px;");
		
		// botonEnvCantLegajos
		botonEnvCantLegajos = new Button();
		botonEnvCantLegajos.setCaption("M");
		botonEnvCantLegajos.setImmediate(true);
		botonEnvCantLegajos.setWidth("-1px");
		botonEnvCantLegajos.setHeight("-1px");
		LayoutUbicacion.addComponent(botonEnvCantLegajos, "top:330.0px;left:200.0px;");
		
		return LayoutUbicacion;
	}

	@AutoGenerated
	private AbsoluteLayout buildLayoutFechas() {
		// common part: create layout
		LayoutFechas = new AbsoluteLayout();
		LayoutFechas.setImmediate(false);
		LayoutFechas.setWidth("100.0%");
		LayoutFechas.setHeight("100.0%");
		
		// labelFechaCambioEstado
		labelFechaCambioEstado = new Label();
		labelFechaCambioEstado.setImmediate(false);
		labelFechaCambioEstado.setWidth("-1px");
		labelFechaCambioEstado.setHeight("-1px");
		labelFechaCambioEstado.setValue("Fecha Cambio Estado:");
		LayoutFechas.addComponent(labelFechaCambioEstado, "top:200.0px;left:0.0px;");
		
		// valorFechaCambioEstado
		valorFechaCambioEstado = new Label();
		valorFechaCambioEstado.setImmediate(false);
		valorFechaCambioEstado.setWidth("-1px");
		valorFechaCambioEstado.setHeight("-1px");
		valorFechaCambioEstado.setValue("Label");
		LayoutFechas.addComponent(valorFechaCambioEstado, "top:240.0px;left:0.0px;");
		
		// botonModFechaCambioEstado
		botonModFechaCambioEstado = new Button();
		botonModFechaCambioEstado.setCaption("Modificar");
		botonModFechaCambioEstado.setImmediate(true);
		botonModFechaCambioEstado.setWidth("-1px");
		botonModFechaCambioEstado.setHeight("-1px");
		LayoutFechas.addComponent(botonModFechaCambioEstado, "top:280.0px;left:0.0px;");
		
		// campoFechaCambioEstado
		campoFechaCambioEstado = new TextField();
		campoFechaCambioEstado.setImmediate(false);
		campoFechaCambioEstado.setWidth("-1px");
		campoFechaCambioEstado.setHeight("-1px");
		LayoutFechas.addComponent(campoFechaCambioEstado, "top:330.0px;left:0.0px;");
		
		// botonEnvFechaCambioEstado
		botonEnvFechaCambioEstado = new Button();
		botonEnvFechaCambioEstado.setCaption("M");
		botonEnvFechaCambioEstado.setImmediate(true);
		botonEnvFechaCambioEstado.setWidth("-1px");
		botonEnvFechaCambioEstado.setHeight("-1px");
		LayoutFechas.addComponent(botonEnvFechaCambioEstado, "top:330.0px;left:200.0px;");
		
		// labelFechaUltUbicacion
		labelFechaUltUbicacion = new Label();
		labelFechaUltUbicacion.setImmediate(false);
		labelFechaUltUbicacion.setWidth("-1px");
		labelFechaUltUbicacion.setHeight("-1px");
		labelFechaUltUbicacion.setValue("Fecha Última Ubicación:");
		LayoutFechas.addComponent(labelFechaUltUbicacion, "top:400.0px;left:0.0px;");
		
		// valorFechaUltUbicacion
		valorFechaUltUbicacion = new Label();
		valorFechaUltUbicacion.setImmediate(false);
		valorFechaUltUbicacion.setWidth("-1px");
		valorFechaUltUbicacion.setHeight("-1px");
		valorFechaUltUbicacion.setValue("Label");
		LayoutFechas.addComponent(valorFechaUltUbicacion, "top:440.0px;left:0.0px;");
		
		// botonModFechaUltUbicacion
		botonModFechaUltUbicacion = new Button();
		botonModFechaUltUbicacion.setCaption("Modificar");
		botonModFechaUltUbicacion.setImmediate(true);
		botonModFechaUltUbicacion.setWidth("-1px");
		botonModFechaUltUbicacion.setHeight("-1px");
		LayoutFechas.addComponent(botonModFechaUltUbicacion, "top:480.0px;left:0.0px;");
		
		// campoFechaUltUbicacion
		campoFechaUltUbicacion = new TextField();
		campoFechaUltUbicacion.setImmediate(false);
		campoFechaUltUbicacion.setWidth("-1px");
		campoFechaUltUbicacion.setHeight("-1px");
		LayoutFechas.addComponent(campoFechaUltUbicacion, "top:530.0px;left:0.0px;");
		
		// botonEnvFechaUltUbicacion
		botonEnvFechaUltUbicacion = new Button();
		botonEnvFechaUltUbicacion.setCaption("M");
		botonEnvFechaUltUbicacion.setImmediate(true);
		botonEnvFechaUltUbicacion.setWidth("-1px");
		botonEnvFechaUltUbicacion.setHeight("-1px");
		LayoutFechas.addComponent(botonEnvFechaUltUbicacion, "top:530.0px;left:200.0px;");
		
		// labelFechaPresentacion
		labelFechaPresentacion = new Label();
		labelFechaPresentacion.setImmediate(false);
		labelFechaPresentacion.setWidth("-1px");
		labelFechaPresentacion.setHeight("-1px");
		labelFechaPresentacion.setValue("Fecha Presentación:");
		LayoutFechas.addComponent(labelFechaPresentacion, "top:0.0px;");
		
		// valorFechaPresentacion
		valorFechaPresentacion = new Label();
		valorFechaPresentacion.setImmediate(false);
		valorFechaPresentacion.setWidth("-1px");
		valorFechaPresentacion.setHeight("-1px");
		valorFechaPresentacion.setValue("Label");
		LayoutFechas.addComponent(valorFechaPresentacion, "top:40.0px;left:0.0px;");
		
		// botonModFechaPresentacion
		botonModFechaPresentacion = new Button();
		botonModFechaPresentacion.setCaption("Modificar");
		botonModFechaPresentacion.setImmediate(true);
		botonModFechaPresentacion.setWidth("-1px");
		botonModFechaPresentacion.setHeight("-1px");
		LayoutFechas.addComponent(botonModFechaPresentacion, "top:80.0px;left:0.0px;");
		
		// campoFechaPresentacion
		campoFechaPresentacion = new TextField();
		campoFechaPresentacion.setImmediate(false);
		campoFechaPresentacion.setWidth("-1px");
		campoFechaPresentacion.setHeight("-1px");
		LayoutFechas.addComponent(campoFechaPresentacion, "top:130.0px;");
		
		// botonEnvFechaPresentacion
		botonEnvFechaPresentacion = new Button();
		botonEnvFechaPresentacion.setCaption("M");
		botonEnvFechaPresentacion.setImmediate(true);
		botonEnvFechaPresentacion.setWidth("-1px");
		botonEnvFechaPresentacion.setHeight("-1px");
		LayoutFechas.addComponent(botonEnvFechaPresentacion, "top:130.0px;left:200.0px;");
		
		// labelDuracPresentacionIngreso
		labelDuracPresentacionIngreso = new Label();
		labelDuracPresentacionIngreso.setImmediate(false);
		labelDuracPresentacionIngreso.setWidth("-1px");
		labelDuracPresentacionIngreso.setHeight("-1px");
		labelDuracPresentacionIngreso.setValue("Duración Presentación-Ingreso:");
		LayoutFechas.addComponent(labelDuracPresentacionIngreso, "top:0.0px;left:700.0px;");
		
		// valorDuracPresentacionIngreso
		valorDuracPresentacionIngreso = new Label();
		valorDuracPresentacionIngreso.setImmediate(false);
		valorDuracPresentacionIngreso.setWidth("-1px");
		valorDuracPresentacionIngreso.setHeight("-1px");
		valorDuracPresentacionIngreso.setValue("Label");
		LayoutFechas.addComponent(valorDuracPresentacionIngreso, "top:40.0px;left:700.0px;");
		
		// botonModDuracPresentacionIngreso
		botonModDuracPresentacionIngreso = new Button();
		botonModDuracPresentacionIngreso.setCaption("Modificar");
		botonModDuracPresentacionIngreso.setImmediate(true);
		botonModDuracPresentacionIngreso.setWidth("-1px");
		botonModDuracPresentacionIngreso.setHeight("-1px");
		LayoutFechas.addComponent(botonModDuracPresentacionIngreso, "top:80.0px;left:700.0px;");
		
		// campoDuracPresentacionIngreso
		campoDuracPresentacionIngreso = new TextField();
		campoDuracPresentacionIngreso.setImmediate(false);
		campoDuracPresentacionIngreso.setWidth("-1px");
		campoDuracPresentacionIngreso.setHeight("-1px");
		LayoutFechas.addComponent(campoDuracPresentacionIngreso, "top:130.0px;left:700.0px;");
		
		// botonEnvDuracPresentacionIngreso
		botonEnvDuracPresentacionIngreso = new Button();
		botonEnvDuracPresentacionIngreso.setCaption("M");
		botonEnvDuracPresentacionIngreso.setImmediate(true);
		botonEnvDuracPresentacionIngreso.setWidth("-1px");
		botonEnvDuracPresentacionIngreso.setHeight("-1px");
		LayoutFechas.addComponent(botonEnvDuracPresentacionIngreso, "top:130.0px;left:900.0px;");
		
		// labelDuracIngresoCambio
		labelDuracIngresoCambio = new Label();
		labelDuracIngresoCambio.setImmediate(false);
		labelDuracIngresoCambio.setWidth("-1px");
		labelDuracIngresoCambio.setHeight("-1px");
		labelDuracIngresoCambio.setValue("Duración Ingreso-Cambio Estado:");
		LayoutFechas.addComponent(labelDuracIngresoCambio, "top:200.0px;left:700.0px;");
		
		// valorDuracIngresoCambio
		valorDuracIngresoCambio = new Label();
		valorDuracIngresoCambio.setImmediate(false);
		valorDuracIngresoCambio.setWidth("-1px");
		valorDuracIngresoCambio.setHeight("-1px");
		valorDuracIngresoCambio.setValue("Label");
		LayoutFechas.addComponent(valorDuracIngresoCambio, "top:240.0px;left:700.0px;");
		
		// botonModDuracIngresoCambio
		botonModDuracIngresoCambio = new Button();
		botonModDuracIngresoCambio.setCaption("Modificar");
		botonModDuracIngresoCambio.setImmediate(true);
		botonModDuracIngresoCambio.setWidth("-1px");
		botonModDuracIngresoCambio.setHeight("-1px");
		LayoutFechas.addComponent(botonModDuracIngresoCambio, "top:280.0px;left:700.0px;");
		
		// campoDuracIngresoCambio
		campoDuracIngresoCambio = new TextField();
		campoDuracIngresoCambio.setImmediate(false);
		campoDuracIngresoCambio.setWidth("-1px");
		campoDuracIngresoCambio.setHeight("-1px");
		LayoutFechas.addComponent(campoDuracIngresoCambio, "top:330.0px;left:700.0px;");
		
		// botonEnvDuracIngresoCambio
		botonEnvDuracIngresoCambio = new Button();
		botonEnvDuracIngresoCambio.setCaption("M");
		botonEnvDuracIngresoCambio.setImmediate(true);
		botonEnvDuracIngresoCambio.setWidth("-1px");
		botonEnvDuracIngresoCambio.setHeight("-1px");
		LayoutFechas.addComponent(botonEnvDuracIngresoCambio, "top:330.0px;left:900.0px;");
		
		// labelPlazoIngresoCambio
		labelPlazoIngresoCambio = new Label();
		labelPlazoIngresoCambio.setImmediate(false);
		labelPlazoIngresoCambio.setWidth("-1px");
		labelPlazoIngresoCambio.setHeight("-1px");
		labelPlazoIngresoCambio.setValue("Plazo Ingreso-Cambio Estado:");
		LayoutFechas.addComponent(labelPlazoIngresoCambio, "top:200.0px;left:350.0px;");
		
		// valorPlazoIngresoCambio
		valorPlazoIngresoCambio = new Label();
		valorPlazoIngresoCambio.setImmediate(false);
		valorPlazoIngresoCambio.setWidth("-1px");
		valorPlazoIngresoCambio.setHeight("-1px");
		valorPlazoIngresoCambio.setValue("Label");
		LayoutFechas.addComponent(valorPlazoIngresoCambio, "top:240.0px;left:350.0px;");
		
		// botonModPlazoIngresoCambio
		botonModPlazoIngresoCambio = new Button();
		botonModPlazoIngresoCambio.setCaption("Modificar");
		botonModPlazoIngresoCambio.setImmediate(true);
		botonModPlazoIngresoCambio.setWidth("-1px");
		botonModPlazoIngresoCambio.setHeight("-1px");
		LayoutFechas.addComponent(botonModPlazoIngresoCambio, "top:280.0px;left:350.0px;");
		
		// campoPlazoIngresoCambio
		campoPlazoIngresoCambio = new TextField();
		campoPlazoIngresoCambio.setImmediate(false);
		campoPlazoIngresoCambio.setWidth("-1px");
		campoPlazoIngresoCambio.setHeight("-1px");
		LayoutFechas.addComponent(campoPlazoIngresoCambio, "top:330.0px;left:350.0px;");
		
		// botonEnvPlazoIngresoCambio
		botonEnvPlazoIngresoCambio = new Button();
		botonEnvPlazoIngresoCambio.setCaption("M");
		botonEnvPlazoIngresoCambio.setImmediate(true);
		botonEnvPlazoIngresoCambio.setWidth("-1px");
		botonEnvPlazoIngresoCambio.setHeight("-1px");
		LayoutFechas.addComponent(botonEnvPlazoIngresoCambio, "top:330.0px;left:550.0px;");
		
		// labelDuracIngresoUltUbic
		labelDuracIngresoUltUbic = new Label();
		labelDuracIngresoUltUbic.setImmediate(false);
		labelDuracIngresoUltUbic.setWidth("-1px");
		labelDuracIngresoUltUbic.setHeight("-1px");
		labelDuracIngresoUltUbic.setValue("Duración Ingreso-Última Ubicación");
		LayoutFechas.addComponent(labelDuracIngresoUltUbic, "top:400.0px;left:700.0px;");
		
		// valorDuracIngresoUltUbic
		valorDuracIngresoUltUbic = new Label();
		valorDuracIngresoUltUbic.setImmediate(false);
		valorDuracIngresoUltUbic.setWidth("-1px");
		valorDuracIngresoUltUbic.setHeight("-1px");
		valorDuracIngresoUltUbic.setValue("Label");
		LayoutFechas.addComponent(valorDuracIngresoUltUbic, "top:440.0px;left:700.0px;");
		
		// botonModDuracIngresoUltUbic
		botonModDuracIngresoUltUbic = new Button();
		botonModDuracIngresoUltUbic.setCaption("Modificar");
		botonModDuracIngresoUltUbic.setImmediate(true);
		botonModDuracIngresoUltUbic.setWidth("-1px");
		botonModDuracIngresoUltUbic.setHeight("-1px");
		LayoutFechas.addComponent(botonModDuracIngresoUltUbic, "top:480.0px;left:700.0px;");
		
		// campoDuracIngresoUltUbic
		campoDuracIngresoUltUbic = new TextField();
		campoDuracIngresoUltUbic.setImmediate(false);
		campoDuracIngresoUltUbic.setWidth("-1px");
		campoDuracIngresoUltUbic.setHeight("-1px");
		LayoutFechas.addComponent(campoDuracIngresoUltUbic, "top:530.0px;left:700.0px;");
		
		// botonEnvDuracIngresoUltUbic
		botonEnvDuracIngresoUltUbic = new Button();
		botonEnvDuracIngresoUltUbic.setCaption("M");
		botonEnvDuracIngresoUltUbic.setImmediate(true);
		botonEnvDuracIngresoUltUbic.setWidth("-1px");
		botonEnvDuracIngresoUltUbic.setHeight("-1px");
		LayoutFechas.addComponent(botonEnvDuracIngresoUltUbic, "top:530.0px;left:900.0px;");
		
		// labelFechaIng
		labelFechaIng = new Label();
		labelFechaIng.setImmediate(false);
		labelFechaIng.setWidth("-1px");
		labelFechaIng.setHeight("-1px");
		labelFechaIng.setValue("Fecha Ingreso Denuncia:");
		LayoutFechas.addComponent(labelFechaIng, "top:0.0px;left:350.0px;");
		
		// valorFechaIng
		valorFechaIng = new Label();
		valorFechaIng.setImmediate(false);
		valorFechaIng.setWidth("-1px");
		valorFechaIng.setHeight("-1px");
		valorFechaIng.setValue("Label");
		LayoutFechas.addComponent(valorFechaIng, "top:40.0px;left:350.0px;");
		
		// botonModFechaIng
		botonModFechaIng = new Button();
		botonModFechaIng.setCaption("Modificar");
		botonModFechaIng.setImmediate(true);
		botonModFechaIng.setWidth("-1px");
		botonModFechaIng.setHeight("-1px");
		LayoutFechas.addComponent(botonModFechaIng, "top:80.0px;left:350.0px;");
		
		// campoFechaIng
		campoFechaIng = new TextField();
		campoFechaIng.setImmediate(false);
		campoFechaIng.setWidth("-1px");
		campoFechaIng.setHeight("-1px");
		LayoutFechas.addComponent(campoFechaIng, "top:130.0px;left:350.0px;");
		
		// botonEnvFechaIng
		botonEnvFechaIng = new Button();
		botonEnvFechaIng.setCaption("M");
		botonEnvFechaIng.setImmediate(true);
		botonEnvFechaIng.setWidth("-1px");
		botonEnvFechaIng.setHeight("-1px");
		LayoutFechas.addComponent(botonEnvFechaIng, "top:130.0px;left:550.0px;");
		
		// labelPlazoIngresoUltUbic
		labelPlazoIngresoUltUbic = new Label();
		labelPlazoIngresoUltUbic.setImmediate(false);
		labelPlazoIngresoUltUbic.setWidth("-1px");
		labelPlazoIngresoUltUbic.setHeight("-1px");
		labelPlazoIngresoUltUbic.setValue("Plazo Ingreso-Última Ubicación");
		LayoutFechas.addComponent(labelPlazoIngresoUltUbic, "top:400.0px;left:350.0px;");
		
		// valorPlazoIngresoUltUbic
		valorPlazoIngresoUltUbic = new Label();
		valorPlazoIngresoUltUbic.setImmediate(false);
		valorPlazoIngresoUltUbic.setWidth("-1px");
		valorPlazoIngresoUltUbic.setHeight("-1px");
		valorPlazoIngresoUltUbic.setValue("Label");
		LayoutFechas.addComponent(valorPlazoIngresoUltUbic, "top:440.0px;left:350.0px;");
		
		// botonModPlazoIngresoUltUbic
		botonModPlazoIngresoUltUbic = new Button();
		botonModPlazoIngresoUltUbic.setCaption("Modificar");
		botonModPlazoIngresoUltUbic.setImmediate(true);
		botonModPlazoIngresoUltUbic.setWidth("-1px");
		botonModPlazoIngresoUltUbic.setHeight("-1px");
		LayoutFechas.addComponent(botonModPlazoIngresoUltUbic, "top:480.0px;left:350.0px;");
		
		// campoPlazoIngresoUltUbic
		campoPlazoIngresoUltUbic = new TextField();
		campoPlazoIngresoUltUbic.setImmediate(false);
		campoPlazoIngresoUltUbic.setWidth("-1px");
		campoPlazoIngresoUltUbic.setHeight("-1px");
		LayoutFechas.addComponent(campoPlazoIngresoUltUbic, "top:530.0px;left:350.0px;");
		
		// botonEnvPlazoIngresoUltUbic
		botonEnvPlazoIngresoUltUbic = new Button();
		botonEnvPlazoIngresoUltUbic.setCaption("M");
		botonEnvPlazoIngresoUltUbic.setImmediate(true);
		botonEnvPlazoIngresoUltUbic.setWidth("-1px");
		botonEnvPlazoIngresoUltUbic.setHeight("-1px");
		LayoutFechas.addComponent(botonEnvPlazoIngresoUltUbic, "top:530.0px;left:550.0px;");
		
		// labelDuracCambioUltUbic
		labelDuracCambioUltUbic = new Label();
		labelDuracCambioUltUbic.setImmediate(false);
		labelDuracCambioUltUbic.setWidth("-1px");
		labelDuracCambioUltUbic.setHeight("-1px");
		labelDuracCambioUltUbic.setValue("Duración Cambio Estado-Última Ubicación");
		LayoutFechas.addComponent(labelDuracCambioUltUbic, "top:600.0px;left:0.0px;");
		
		// valorDuracCambioUltUbic
		valorDuracCambioUltUbic = new Label();
		valorDuracCambioUltUbic.setImmediate(false);
		valorDuracCambioUltUbic.setWidth("-1px");
		valorDuracCambioUltUbic.setHeight("-1px");
		valorDuracCambioUltUbic.setValue("Label");
		LayoutFechas.addComponent(valorDuracCambioUltUbic, "top:640.0px;left:0.0px;");
		
		// botonModDuracCambioUltUbic
		botonModDuracCambioUltUbic = new Button();
		botonModDuracCambioUltUbic.setCaption("Modificar");
		botonModDuracCambioUltUbic.setImmediate(true);
		botonModDuracCambioUltUbic.setWidth("-1px");
		botonModDuracCambioUltUbic.setHeight("-1px");
		LayoutFechas.addComponent(botonModDuracCambioUltUbic, "top:680.0px;left:0.0px;");
		
		// campoDuracCambioUltUbic
		campoDuracCambioUltUbic = new TextField();
		campoDuracCambioUltUbic.setImmediate(false);
		campoDuracCambioUltUbic.setWidth("-1px");
		campoDuracCambioUltUbic.setHeight("-1px");
		LayoutFechas.addComponent(campoDuracCambioUltUbic, "top:730.0px;left:0.0px;");
		
		// botonEnvDuracCambioUltUbic
		botonEnvDuracCambioUltUbic = new Button();
		botonEnvDuracCambioUltUbic.setCaption("M");
		botonEnvDuracCambioUltUbic.setImmediate(true);
		botonEnvDuracCambioUltUbic.setWidth("-1px");
		botonEnvDuracCambioUltUbic.setHeight("-1px");
		LayoutFechas.addComponent(botonEnvDuracCambioUltUbic, "top:730.0px;left:200.0px;");
		
		return LayoutFechas;
	}

}
