package ucr.casoUso;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;

public class VistaCrearExpediente extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":7} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button buttonVolver;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_4;
	@AutoGenerated
	private TextField textFieldCausa;
	@AutoGenerated
	private TextField textFieldFechaUbic;
	@AutoGenerated
	private TextField textFieldUbicacion;
	@AutoGenerated
	private Label labelCausa;
	@AutoGenerated
	private Label labelFechaUbic;
	@AutoGenerated
	private Label labelUbicacion;
	@AutoGenerated
	private Label labelInfoAdicional;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_3;
	@AutoGenerated
	private TextField textFieldFechaIngresoDenun;
	@AutoGenerated
	private Label labelFechaIngresoDenun;
	@AutoGenerated
	private TextField textFieldFechaDenun;
	@AutoGenerated
	private Label labelFechaDenum;
	@AutoGenerated
	private TextField textFieldSede;
	@AutoGenerated
	private Label labelSede;
	@AutoGenerated
	private TextField textFieldInstrCargo;
	@AutoGenerated
	private Label labelInstrCargo;
	@AutoGenerated
	private TextField textFieldNumExpediente;
	@AutoGenerated
	private Label labelNumExpediente;
	@AutoGenerated
	private Label labelInfoGenerak;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_2;
	@AutoGenerated
	private TextField textFieldParteDenunciante;
	@AutoGenerated
	private Label labelParteDenunciante;
	@AutoGenerated
	private TextField textFieldIndentif;
	@AutoGenerated
	private Label labelIdentif;
	@AutoGenerated
	private TextField textFieldParteDenunciada;
	@AutoGenerated
	private Label labelParteDenunciada;
	@AutoGenerated
	private TextField textFieldCarnet;
	@AutoGenerated
	private Label labelCarnet;
	@AutoGenerated
	private Label labelInfoPartes;
	@AutoGenerated
	private Label labelTitulo;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public VistaCrearExpediente() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("1000px");
		mainLayout.setHeight("650px");
		
		// top-level component properties
		setWidth("1000px");
		setHeight("650px");
		
		// labelTitulo
		labelTitulo = new Label();
		labelTitulo.setImmediate(false);
		labelTitulo.setWidth("-1px");
		labelTitulo.setHeight("-1px");
		labelTitulo.setValue("Crear Expediente");
		mainLayout.addComponent(labelTitulo, "top:60.0px;left:80.0px;");
		
		// absoluteLayout_2
		absoluteLayout_2 = buildAbsoluteLayout_2();
		mainLayout.addComponent(absoluteLayout_2, "top:100.0px;left:389.0px;");
		
		// absoluteLayout_3
		absoluteLayout_3 = buildAbsoluteLayout_3();
		mainLayout.addComponent(absoluteLayout_3, "top:100.0px;left:60.0px;");
		
		// absoluteLayout_4
		absoluteLayout_4 = buildAbsoluteLayout_4();
		mainLayout.addComponent(absoluteLayout_4, "top:100.0px;left:645.0px;");
		
		// buttonVolver
		buttonVolver = new Button();
		buttonVolver.setCaption("Volver");
		buttonVolver.setImmediate(false);
		buttonVolver.setWidth("80px");
		buttonVolver.setHeight("-1px");
		mainLayout.addComponent(buttonVolver, "top:560.0px;right:90.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_2() {
		// common part: create layout
		absoluteLayout_2 = new AbsoluteLayout();
		absoluteLayout_2.setImmediate(false);
		absoluteLayout_2.setWidth("211px");
		absoluteLayout_2.setHeight("384px");
		
		// labelInfoPartes
		labelInfoPartes = new Label();
		labelInfoPartes.setImmediate(false);
		labelInfoPartes.setWidth("-1px");
		labelInfoPartes.setHeight("-1px");
		labelInfoPartes.setValue("Información de las Partes");
		absoluteLayout_2.addComponent(labelInfoPartes, "top:8.0px;left:10.0px;");
		
		// labelCarnet
		labelCarnet = new Label();
		labelCarnet.setImmediate(false);
		labelCarnet.setWidth("-1px");
		labelCarnet.setHeight("-1px");
		labelCarnet.setValue("Carnet");
		absoluteLayout_2.addComponent(labelCarnet, "top:45.0px;left:12.0px;");
		
		// textFieldCarnet
		textFieldCarnet = new TextField();
		textFieldCarnet.setImmediate(false);
		textFieldCarnet.setWidth("-1px");
		textFieldCarnet.setHeight("-1px");
		textFieldCarnet.setRequired(true);
		absoluteLayout_2.addComponent(textFieldCarnet, "top:80.0px;left:10.0px;");
		
		// labelParteDenunciada
		labelParteDenunciada = new Label();
		labelParteDenunciada.setImmediate(false);
		labelParteDenunciada.setWidth("-1px");
		labelParteDenunciada.setHeight("-1px");
		labelParteDenunciada.setValue("Parte Denunciada");
		absoluteLayout_2.addComponent(labelParteDenunciada, "top:128.0px;left:11.0px;");
		
		// textFieldParteDenunciada
		textFieldParteDenunciada = new TextField();
		textFieldParteDenunciada.setImmediate(false);
		textFieldParteDenunciada.setWidth("-1px");
		textFieldParteDenunciada.setHeight("-1px");
		textFieldParteDenunciada.setRequired(true);
		absoluteLayout_2.addComponent(textFieldParteDenunciada, "top:165.0px;left:10.0px;");
		
		// labelIdentif
		labelIdentif = new Label();
		labelIdentif.setImmediate(false);
		labelIdentif.setWidth("-1px");
		labelIdentif.setHeight("-1px");
		labelIdentif.setValue("Identificación");
		absoluteLayout_2.addComponent(labelIdentif, "top:206.0px;left:12.0px;");
		
		// textFieldIndentif
		textFieldIndentif = new TextField();
		textFieldIndentif.setImmediate(false);
		textFieldIndentif.setWidth("-1px");
		textFieldIndentif.setHeight("-1px");
		textFieldIndentif.setRequired(true);
		absoluteLayout_2.addComponent(textFieldIndentif, "top:241.0px;left:11.0px;");
		
		// labelParteDenunciante
		labelParteDenunciante = new Label();
		labelParteDenunciante.setImmediate(false);
		labelParteDenunciante.setWidth("-1px");
		labelParteDenunciante.setHeight("-1px");
		labelParteDenunciante.setValue("Parte Denunciante");
		absoluteLayout_2.addComponent(labelParteDenunciante, "top:286.0px;left:12.0px;");
		
		// textFieldParteDenunciante
		textFieldParteDenunciante = new TextField();
		textFieldParteDenunciante.setImmediate(false);
		textFieldParteDenunciante.setWidth("-1px");
		textFieldParteDenunciante.setHeight("-1px");
		textFieldParteDenunciante.setRequired(true);
		absoluteLayout_2.addComponent(textFieldParteDenunciante, "top:320.0px;left:10.0px;");
		
		return absoluteLayout_2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_3() {
		// common part: create layout
		absoluteLayout_3 = new AbsoluteLayout();
		absoluteLayout_3.setImmediate(false);
		absoluteLayout_3.setWidth("280px");
		absoluteLayout_3.setHeight("460px");
		
		// labelInfoGenerak
		labelInfoGenerak = new Label();
		labelInfoGenerak.setImmediate(false);
		labelInfoGenerak.setWidth("-1px");
		labelInfoGenerak.setHeight("-1px");
		labelInfoGenerak.setValue("Información General del Expediente");
		absoluteLayout_3.addComponent(labelInfoGenerak, "top:4.0px;left:6.0px;");
		
		// labelNumExpediente
		labelNumExpediente = new Label();
		labelNumExpediente.setImmediate(false);
		labelNumExpediente.setWidth("-1px");
		labelNumExpediente.setHeight("-1px");
		labelNumExpediente.setValue("Número de Expediente");
		absoluteLayout_3.addComponent(labelNumExpediente, "top:44.0px;left:20.0px;");
		
		// textFieldNumExpediente
		textFieldNumExpediente = new TextField();
		textFieldNumExpediente.setImmediate(false);
		textFieldNumExpediente.setWidth("-1px");
		textFieldNumExpediente.setHeight("-1px");
		textFieldNumExpediente.setRequired(true);
		absoluteLayout_3.addComponent(textFieldNumExpediente, "top:80.0px;left:19.0px;");
		
		// labelInstrCargo
		labelInstrCargo = new Label();
		labelInstrCargo.setImmediate(false);
		labelInstrCargo.setWidth("-1px");
		labelInstrCargo.setHeight("-1px");
		labelInstrCargo.setValue("Instructor a Cargo");
		absoluteLayout_3.addComponent(labelInstrCargo, "top:122.0px;left:21.0px;");
		
		// textFieldInstrCargo
		textFieldInstrCargo = new TextField();
		textFieldInstrCargo.setImmediate(false);
		textFieldInstrCargo.setWidth("-1px");
		textFieldInstrCargo.setHeight("-1px");
		textFieldInstrCargo.setRequired(true);
		absoluteLayout_3.addComponent(textFieldInstrCargo, "top:160.0px;left:19.0px;");
		
		// labelSede
		labelSede = new Label();
		labelSede.setImmediate(false);
		labelSede.setWidth("-1px");
		labelSede.setHeight("-1px");
		labelSede.setValue("Sede");
		absoluteLayout_3.addComponent(labelSede, "top:203.0px;left:20.0px;");
		
		// textFieldSede
		textFieldSede = new TextField();
		textFieldSede.setImmediate(false);
		textFieldSede.setWidth("-1px");
		textFieldSede.setHeight("-1px");
		textFieldSede.setRequired(true);
		absoluteLayout_3.addComponent(textFieldSede, "top:240.0px;left:20.0px;");
		
		// labelFechaDenum
		labelFechaDenum = new Label();
		labelFechaDenum.setImmediate(false);
		labelFechaDenum.setWidth("-1px");
		labelFechaDenum.setHeight("-1px");
		labelFechaDenum.setValue("Fecha de Denuncia");
		absoluteLayout_3.addComponent(labelFechaDenum, "top:281.0px;left:20.0px;");
		
		// textFieldFechaDenun
		textFieldFechaDenun = new TextField();
		textFieldFechaDenun.setImmediate(false);
		textFieldFechaDenun.setWidth("-1px");
		textFieldFechaDenun.setHeight("-1px");
		textFieldFechaDenun.setRequired(true);
		absoluteLayout_3.addComponent(textFieldFechaDenun, "top:322.0px;left:21.0px;");
		
		// labelFechaIngresoDenun
		labelFechaIngresoDenun = new Label();
		labelFechaIngresoDenun.setImmediate(false);
		labelFechaIngresoDenun.setWidth("-1px");
		labelFechaIngresoDenun.setHeight("-1px");
		labelFechaIngresoDenun.setValue("Fecha de ingreso de la Denuncia");
		absoluteLayout_3.addComponent(labelFechaIngresoDenun, "top:360.0px;left:21.0px;");
		
		// textFieldFechaIngresoDenun
		textFieldFechaIngresoDenun = new TextField();
		textFieldFechaIngresoDenun.setImmediate(false);
		textFieldFechaIngresoDenun.setWidth("-1px");
		textFieldFechaIngresoDenun.setHeight("-1px");
		textFieldFechaIngresoDenun.setRequired(true);
		absoluteLayout_3.addComponent(textFieldFechaIngresoDenun, "top:400.0px;left:19.0px;");
		
		return absoluteLayout_3;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_4() {
		// common part: create layout
		absoluteLayout_4 = new AbsoluteLayout();
		absoluteLayout_4.setImmediate(false);
		absoluteLayout_4.setWidth("264px");
		absoluteLayout_4.setHeight("365px");
		
		// labelInfoAdicional
		labelInfoAdicional = new Label();
		labelInfoAdicional.setImmediate(false);
		labelInfoAdicional.setWidth("-1px");
		labelInfoAdicional.setHeight("-1px");
		labelInfoAdicional.setValue("Información Adicional del Expediente");
		absoluteLayout_4.addComponent(labelInfoAdicional, "top:20.0px;left:9.0px;");
		
		// labelUbicacion
		labelUbicacion = new Label();
		labelUbicacion.setImmediate(false);
		labelUbicacion.setWidth("-1px");
		labelUbicacion.setHeight("-1px");
		labelUbicacion.setValue("Ubicación");
		absoluteLayout_4.addComponent(labelUbicacion, "top:45.0px;left:15.0px;");
		
		// labelFechaUbic
		labelFechaUbic = new Label();
		labelFechaUbic.setImmediate(false);
		labelFechaUbic.setWidth("-1px");
		labelFechaUbic.setHeight("-1px");
		labelFechaUbic.setValue("Fecha de Última Ubicación");
		absoluteLayout_4.addComponent(labelFechaUbic, "top:122.0px;left:15.0px;");
		
		// labelCausa
		labelCausa = new Label();
		labelCausa.setImmediate(false);
		labelCausa.setWidth("-1px");
		labelCausa.setHeight("-1px");
		labelCausa.setValue("Causa");
		absoluteLayout_4.addComponent(labelCausa, "top:203.0px;left:15.0px;");
		
		// textFieldUbicacion
		textFieldUbicacion = new TextField();
		textFieldUbicacion.setImmediate(false);
		textFieldUbicacion.setWidth("-1px");
		textFieldUbicacion.setHeight("-1px");
		textFieldUbicacion.setRequired(true);
		absoluteLayout_4.addComponent(textFieldUbicacion, "top:80.0px;left:14.0px;");
		
		// textFieldFechaUbic
		textFieldFechaUbic = new TextField();
		textFieldFechaUbic.setImmediate(false);
		textFieldFechaUbic.setWidth("-1px");
		textFieldFechaUbic.setHeight("-1px");
		textFieldFechaUbic.setRequired(true);
		absoluteLayout_4.addComponent(textFieldFechaUbic, "top:158.0px;left:15.0px;");
		
		// textFieldCausa
		textFieldCausa = new TextField();
		textFieldCausa.setImmediate(false);
		textFieldCausa.setWidth("-1px");
		textFieldCausa.setHeight("-1px");
		textFieldCausa.setRequired(true);
		absoluteLayout_4.addComponent(textFieldCausa, "top:240.0px;left:15.0px;");
		
		return absoluteLayout_4;
	}

}
