package ucr.casoUso;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.event.FieldEvents.TextChangeEvent;
import com.vaadin.event.FieldEvents.TextChangeListener;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;

public class VistaCrearExpediente extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Accordion Acordeon;
	@AutoGenerated
	private AbsoluteLayout LayoutFechas;
	@AutoGenerated
	private TextField campoDuracCambioUltUbic;
	@AutoGenerated
	private TextField campoFechaIng;
	@AutoGenerated
	private Label labelFechaIng;
	@AutoGenerated
	private TextField campoFechaPresentacion;
	@AutoGenerated
	private Label labelFechaPresentacion;
	@AutoGenerated
	private TextField campoFechaUltUbicacion;
	@AutoGenerated
	private Label labelFechaUltUbicacion;
	@AutoGenerated
	private AbsoluteLayout LayoutUbicacion;
	@AutoGenerated
	private TextField campoCantLegajos;
	@AutoGenerated
	private Label labelCantLegajos;
	@AutoGenerated
	private TextField campoUbicLegajos;
	@AutoGenerated
	private Label labelUbicLegajos;
	@AutoGenerated
	private TextField campoMuebleUbicacion;
	@AutoGenerated
	private Label labelMuebleUbicacion;
	@AutoGenerated
	private TextField campoUbicacion;
	@AutoGenerated
	private Label labelUbicacion;
	@AutoGenerated
	private AbsoluteLayout LayoutInfoDenuncia;
	@AutoGenerated
	private TextField campoHoraAudiencia;
	@AutoGenerated
	private Label labelHoraAudiencia;
	@AutoGenerated
	private TextField campoFechaAudiencia;
	@AutoGenerated
	private Label labelFechaAudiencia;
	@AutoGenerated
	private TextField campoArtAplicables;
	@AutoGenerated
	private Label labelArtAplicables;
	@AutoGenerated
	private TextField campoCausa;
	@AutoGenerated
	private Label labelCausa;
	@AutoGenerated
	private TextField campoId;
	@AutoGenerated
	private Label labelId;
	@AutoGenerated
	private TextField campoParteDenunciada;
	@AutoGenerated
	private TextField campoParteDenunciante;
	@AutoGenerated
	private Label labelParteDenunciante;
	@AutoGenerated
	private TextField campoCarnet;
	@AutoGenerated
	private Label labelCarnet;
	@AutoGenerated
	private Label labelParteDenunciada;
	@AutoGenerated
	private TextField campoFechaDenuncia;
	@AutoGenerated
	private Label labelFechaDenuncia;
	@AutoGenerated
	private AbsoluteLayout LayoutInfoGeneral;
	@AutoGenerated
	private Label labelAlertInstructor;
	@AutoGenerated
	private Label labelAlertNumExp;
	@AutoGenerated
	private ComboBox comboBoxClasificacion;
	@AutoGenerated
	private ComboBox comboBoxEstado;
	@AutoGenerated
	private Label labelInstructor;
	@AutoGenerated
	private Label labelNumExp;
	@AutoGenerated
	private TextField campoInstructor;
	@AutoGenerated
	private TextField campoNumExp;
	@AutoGenerated
	private TextField campoResponsable;
	@AutoGenerated
	private Label labelResponsable;
	@AutoGenerated
	private Label labelEstado;
	@AutoGenerated
	private Label labelClas;
	@AutoGenerated
	private Button botonIngresar;
	@AutoGenerated
	private Label labelConfirmacion;
	@AutoGenerated
	private Label valorInst;
	@AutoGenerated
	private Label labelInst;
	@AutoGenerated
	private Button botonVolver;
	private ControladorCrearExpediente controlador;
	private Controlador control;
	
	private String insert = "INSERT INTO expediente ";
	private String consulta = "";
	
	private String valorNumExp;
	private String valorInstructor;
	private String valorResponsable;
	private String valorEstado;
	private String valorClasificacion;
	private String valorCodigo;
	
	private String valorFechaDenuncia;
	private String valorParteDenunciada;
	private String valorCarneDenunciada;
	private String valorParteDenunciante;
	private String valorIdentDenunciante;
	private String valorCausaDenun;
	private String valorArtAplicables;
	private String valorFechaAudiencia;
	private String valorHoraAudiencia;
	
	private String valorUbicacion;
	private String valorMuebleUbi;
	private String valorUbiLegajos;
	private String valorCantidadLegajos;
	
	private String valorFechaPresentacion;
	private String valorFechaIngrDenun;
	private String valorFechaUltimaUbi;
	
	private String valorPlazo;
	
	
	
	
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public VistaCrearExpediente() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		controlador = ControladorCrearExpediente.obtenerInstancia();
		control = Controlador.obtenerInstancia();
		labelAlertNumExp.setVisible(false);
		labelAlertInstructor.setVisible(false);
		llenarComboBoxEstado();
		llenarComboBoxClasif();
		//botonIngresar.setEnabled(false);
		//recordarse de volverlo diseabled cuando inicia.
		
		//Campos de "Informacion General"
		
		campoNumExp.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorNumExp = event.getText();
            	if (!valorNumExp.isEmpty()){
            		System.out.print("\n" + controlador.comprobarNumExp(valorNumExp) + "\n");
            		if (controlador.comprobarNumExp(valorNumExp)){
            			System.out.print("si es vacia\n");
            			labelAlertNumExp.setVisible(false);
            			botonIngresar.setEnabled(true);
            		}
            		else{
            			System.out.print("si no es vacia\n");
            			labelAlertNumExp.setVisible(true);
            			botonIngresar.setEnabled(false);
            		}
            	}
            }
		});
		
		campoInstructor.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorInstructor = event.getText();
            	if (!valorInstructor.isEmpty()){
            		System.out.print("\n" + controlador.comprobarNumExp(valorNumExp) + "\n");
            		if (controlador.comprobarInstructor(valorInstructor)){
            			System.out.print("si es vacia\n");
            			labelAlertInstructor.setVisible(true);
            			botonIngresar.setEnabled(false);
            		}
            		else{
            			System.out.print("si no es vacia\n");
            			labelAlertInstructor.setVisible(false);
            			botonIngresar.setEnabled(true);
            		}
            	}
            }
		});
		
		campoResponsable.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorResponsable  = event.getText();
            }
		});
		
		comboBoxClasificacion.addValueChangeListener(new ValueChangeListener (){
			@Override
			public void valueChange(ValueChangeEvent event){
				if (comboBoxClasificacion.getValue() != null){
					switch(comboBoxClasificacion.getValue().toString()) {
					case "0":
						valorPlazo = "15";
						break;
					case "1":
						valorPlazo = "10";
						break;
					case "2":
						valorPlazo = "22";
						break;
					case "3":
						valorPlazo = "22";
						break;
					case "4":
						valorPlazo = "10";
						break;
					case "5":
						valorPlazo = "66";
						break;
					case "6":
						valorPlazo = "22";
						break;
					case "7":
						valorPlazo = "5";
						break;
					case "8":
						valorPlazo = "15";
						break;
					case "9":
						valorPlazo = "15";
						break;
					case "10":
						valorPlazo = "15";
						break;
					case "11":
						valorPlazo = "132";
						break;
					case "12":
						valorPlazo = "15";
						break;
					case "13":
						valorPlazo = "22";
						break;
					case "14":
						valorPlazo = "117";
						break;
					case "15":
						valorPlazo = "15";
						break;
					case "16":
						valorPlazo = "15";
						break;
					case "17":
						valorPlazo = "44";
						break;
					case "18":
						valorPlazo = "22";
						break;
					case "19":
						valorPlazo = "15";
						break;
					case "20":
						valorPlazo = "22";
						break;
					case "21":
						valorPlazo = "10";
						break;
					case "22":
						valorPlazo = "10";
						break;
					case "23":
						valorPlazo = "15";
						break;
					case "24":
						valorPlazo = "22";
						break;
					case "25":
						valorPlazo = "132";
						break;
					case "26":
						valorPlazo = "132";
						break;
					case "27":
						valorPlazo = "10";
						break;
					case "28":
						valorPlazo = "44";
						break;
					case "29":
						valorPlazo = "10";
						break;
					case "30":
						valorPlazo = "15";
						break;
					case "31":
						valorPlazo = "22";
						break;
					case "32":
						valorPlazo = "44";
						break;
						
					}
				}
			}
		});
		
		
		//Campos de "Informacion de Denuncia"
		
		campoFechaDenuncia.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorFechaDenuncia = event.getText();
            }
		});
		
		campoParteDenunciada.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorParteDenunciada = event.getText();
            }
		});
		
		campoCarnet.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorCarneDenunciada = event.getText();
            }
		});
		
		campoParteDenunciante.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorParteDenunciante = event.getText();
            }
		});
		
		campoId.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorIdentDenunciante = event.getText();
            }
		});
		
		campoCausa.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorCausaDenun = event.getText();
            }
		});
		
		campoArtAplicables.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorArtAplicables = event.getText();
            }
		});
		
		campoFechaAudiencia.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorFechaAudiencia = event.getText();
            }
		});
		
		campoHoraAudiencia.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorHoraAudiencia = event.getText();
            }
		});
		
		//Campos de Ubicacion
		
		campoUbicacion.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorUbicacion = event.getText();
            }
		});
		
		campoMuebleUbicacion.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorMuebleUbi = event.getText();
            }
		});
		
		campoUbicLegajos.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorUbiLegajos = event.getText();
            }
		});
		
		campoCantLegajos.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorCantidadLegajos = event.getText();
            }
		});

		//Campos de Fechas
		
		campoFechaPresentacion.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorFechaPresentacion = event.getText();
            }
		});
		
		campoFechaIng.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorFechaIngrDenun = event.getText();
            }
		});
		
		campoFechaUltUbicacion.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorFechaUltimaUbi = event.getText();
            }
		});
		
		//Botones
		
		botonIngresar.addClickListener(new ClickListener(){
			@Override
			public void buttonClick(ClickEvent evento){
				
				valorCodigo = Integer.toString(controlador.consultarCodigo());
			
				consulta = insert + "VALUES("				+
						"0, " 								+ // Numero de cambios, en 0 por defecto.
						"false, "							+ //archivado, false por defecto
						"'"+valorCodigo+"', "				+ //codigo, valor por defecto?
						"'"+valorNumExp+"', "				+ //numero del expediente
						"'"+valorInstructor+"', "			+ //id Instrcutor
						"'"+valorEstado+"'"					+ //estado
						"'"+valorClasificacion+"', "		+ //clasificacion, da el valor al plazo
						"'"+valorResponsable+"', "			+ //responsable
						"'"+valorFechaDenuncia+"', "		+ //fecha de denuncia
						"'"+valorParteDenunciada+"', "		+ //parte denunciada
						"'"+valorCarneDenunciada+"', "		+ //carne de denunciada
						"'"+valorParteDenunciante+"', "		+ //parte denuncianete
						"'"+valorIdentDenunciante+"', "		+ //id del denunciante
						"'"+valorCausaDenun+"', "			+ //causa de la denuncia
						"'"+valorArtAplicables+"', "		+ //articulos aplicables
						"'"+valorFechaAudiencia+"', "		+ //fecha de audiencia
						"'"+valorHoraAudiencia+"', "		+ //hora de audiencia
						"'"+"plzoMeta"+"', "				+ //plazo meta ?
						"'"+"tiempoTrans"+"', "				+ //tiempo trancurrido ?
						"'"+"condPlazo"+"', "				+ 
						"'"+valorUbicacion+"', "			+ 
						"'"+valorMuebleUbi+"', "			+ 
						"'"+valorUbiLegajos+"', "			+ 
						"'"+valorCantidadLegajos+"', "		+ 
						"'"+valorFechaPresentacion+"', "	+ 
						"'"+valorFechaIngrDenun+"', "		+ 
						"'"+"duracPresIngre"+"', "			+ 
						"'"+"fechaCambiEstado"+"', "		+ 
						"'"+"plazoIngreCambi"+"', "			+ 
						"'"+"duracIngrCamb"+"', "			+ 
						"'"+valorFechaUltimaUbi+"', "		+ 
						"'"+"plazoUltimaUbi"+"', "			+ 
						"'"+"duracIngreUltUbi"+"', "		+ 
						"'"+"duraCambiUltUbi"+"'"			+ 
						");";
				controlador.ingresarExpediente(consulta);	
			}
		});
		
		botonVolver.addClickListener(new ClickListener() {
			@Override
			public void buttonClick (ClickEvent evento){
				control.cambiarVista("Menu Principal");
			}
		});
		
	}
	
	 private void llenarComboBoxEstado(){
		 comboBoxEstado.addItem("Admisibilidad");
		 comboBoxEstado.addItem("Saneamiento");
		 comboBoxEstado.addItem("Comparecencia");
		 comboBoxEstado.addItem("Acto final");
		 comboBoxEstado.addItem("Suspendido");
		 comboBoxEstado.addItem("Terminado");
		 comboBoxEstado.addItem("Términos");
	 }
	 
	 private void llenarComboBoxClasif(){
		 comboBoxClasificacion.addItem("0");
		 comboBoxClasificacion.addItem("1");
		 comboBoxClasificacion.addItem("2");
		 comboBoxClasificacion.addItem("3");
		 comboBoxClasificacion.addItem("4");
		 comboBoxClasificacion.addItem("5");
		 comboBoxClasificacion.addItem("6");
		 comboBoxClasificacion.addItem("7");
		 comboBoxClasificacion.addItem("8");
		 comboBoxClasificacion.addItem("9");
		 comboBoxClasificacion.addItem("10");
		 comboBoxClasificacion.addItem("11");
		 comboBoxClasificacion.addItem("12");
		 comboBoxClasificacion.addItem("13");
		 comboBoxClasificacion.addItem("14");
		 comboBoxClasificacion.addItem("15");
		 comboBoxClasificacion.addItem("16");
		 comboBoxClasificacion.addItem("17");
		 comboBoxClasificacion.addItem("18");
		 comboBoxClasificacion.addItem("19");
		 comboBoxClasificacion.addItem("20");
		 comboBoxClasificacion.addItem("21");
		 comboBoxClasificacion.addItem("22");
		 comboBoxClasificacion.addItem("23");
		 comboBoxClasificacion.addItem("24");
		 comboBoxClasificacion.addItem("25");
		 comboBoxClasificacion.addItem("26");
		 comboBoxClasificacion.addItem("27");
		 comboBoxClasificacion.addItem("28");
		 comboBoxClasificacion.addItem("29");
		 comboBoxClasificacion.addItem("30");
		 comboBoxClasificacion.addItem("31");
		 comboBoxClasificacion.addItem("32");
	 }
	
	
	/*
	private void desaparecerCampos() {
		
		botonAceptar.setVisible(false);
		botonRechazar.setVisible(false);
		labelConfirmacion.setVisible(false);
		campoEstado.setVisible(false);
		campoClas.setVisible(false);
		campoResponsable.setVisible(false);
		campoFechaDenuncia.setVisible(false);

		campoParteDenunciada.setVisible(false);
	
		campoCarnet.setVisible(false);
	
		campoParteDenunciante.setVisible(false);

		campoId.setVisible(false);

		campoCausa.setVisible(false);

		campoArtAplicables.setVisible(false);

		campoFechaAudiencia.setVisible(false);

		campoHoraAudiencia.setVisible(false);

		campoUbicacion.setVisible(false);
		campoMuebleUbicacion.setVisible(false);
		campoUbicLegajos.setVisible(false);
		campoCantLegajos.setVisible(false);
		campoFechaPresentacion.setVisible(false);
		campoFechaIng.setVisible(false);
		
		campoDuracPresentacionIngreso.setVisible(false);
		
		campoFechaCambioEstado.setVisible(false);
	
		campoPlazoIngresoCambio.setVisible(false);
		campoDuracIngresoCambio.setVisible(false);
		
		campoFechaUltUbicacion.setVisible(false);
		
		campoPlazoIngresoUltUbic.setVisible(false);
		
		campoDuracIngresoUltUbic.setVisible(false);
		
		campoDuracCambioUltUbic.setVisible(false);
		
	
	}*/
	
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// botonVolver
		botonVolver = new Button();
		botonVolver.setCaption("Volver");
		botonVolver.setImmediate(true);
		botonVolver.setWidth("-1px");
		botonVolver.setHeight("-1px");
		mainLayout.addComponent(botonVolver, "top:60.0px;left:1000.0px;");
		
		// labelInst
		labelInst = new Label();
		labelInst.setStyleName("error");
		labelInst.setImmediate(false);
		labelInst.setWidth("-1px");
		labelInst.setHeight("-1px");
		labelInst.setValue("Persona a cargo:");
		mainLayout.addComponent(labelInst, "top:150.0px;left:60.0px;");
		
		// valorInst
		valorInst = new Label();
		valorInst.setImmediate(false);
		valorInst.setWidth("-1px");
		valorInst.setHeight("-1px");
		valorInst.setValue("Label");
		mainLayout.addComponent(valorInst, "top:150.0px;left:231.0px;");
		
		// labelConfirmacion
		labelConfirmacion = new Label();
		labelConfirmacion.setImmediate(false);
		labelConfirmacion.setWidth("-1px");
		labelConfirmacion.setHeight("-1px");
		labelConfirmacion.setValue("¿Está seguro que desea ingresar el expediente?");
		mainLayout.addComponent(labelConfirmacion, "top:150.0px;left:569.0px;");
		
		// botonIngresar
		botonIngresar = new Button();
		botonIngresar.setCaption("Ingresar el expediente");
		botonIngresar.setImmediate(true);
		botonIngresar.setWidth("-1px");
		botonIngresar.setHeight("-1px");
		mainLayout.addComponent(botonIngresar, "top:142.0px;left:950.0px;");
		
		// Acordeon
		Acordeon = buildAcordeon();
		mainLayout.addComponent(Acordeon, "top:240.0px;left:60.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private Accordion buildAcordeon() {
		// common part: create layout
		Acordeon = new Accordion();
		Acordeon.setImmediate(true);
		Acordeon.setWidth("90.0%");
		Acordeon.setHeight("90.0%");
		
		// LayoutInfoGeneral
		LayoutInfoGeneral = buildLayoutInfoGeneral();
		Acordeon.addTab(LayoutInfoGeneral, "Información General", null);
		
		// LayoutInfoDenuncia
		LayoutInfoDenuncia = buildLayoutInfoDenuncia();
		Acordeon.addTab(LayoutInfoDenuncia, "Información de la Denuncia", null);
		
		// LayoutUbicacion
		LayoutUbicacion = buildLayoutUbicacion();
		Acordeon.addTab(LayoutUbicacion, "Ubicación", null);
		
		// LayoutFechas
		LayoutFechas = buildLayoutFechas();
		Acordeon.addTab(LayoutFechas, "Fechas", null);
		
		return Acordeon;
	}

	@AutoGenerated
	private AbsoluteLayout buildLayoutInfoGeneral() {
		// common part: create layout
		LayoutInfoGeneral = new AbsoluteLayout();
		LayoutInfoGeneral.setImmediate(false);
		LayoutInfoGeneral.setWidth("100.0%");
		LayoutInfoGeneral.setHeight("100.0%");
		
		// labelClas
		labelClas = new Label();
		labelClas.setImmediate(false);
		labelClas.setWidth("-1px");
		labelClas.setHeight("-1px");
		labelClas.setValue("Clasificación:");
		LayoutInfoGeneral.addComponent(labelClas, "top:200.0px;left:350.0px;");
		
		// labelEstado
		labelEstado = new Label();
		labelEstado.setImmediate(false);
		labelEstado.setWidth("-1px");
		labelEstado.setHeight("-1px");
		labelEstado.setValue("Estado: ");
		LayoutInfoGeneral.addComponent(labelEstado, "top:200.0px;left:0.0px;");
		
		// labelResponsable
		labelResponsable = new Label();
		labelResponsable.setImmediate(false);
		labelResponsable.setWidth("-1px");
		labelResponsable.setHeight("-1px");
		labelResponsable.setValue("Responsable:");
		LayoutInfoGeneral.addComponent(labelResponsable, "top:0.0px;left:700.0px;");
		
		// campoResponsable
		campoResponsable = new TextField();
		campoResponsable.setImmediate(false);
		campoResponsable.setWidth("-1px");
		campoResponsable.setHeight("-1px");
		LayoutInfoGeneral.addComponent(campoResponsable, "top:40.0px;left:700.0px;");
		
		// campoNumExp
		campoNumExp = new TextField();
		campoNumExp.setImmediate(false);
		campoNumExp.setWidth("-1px");
		campoNumExp.setHeight("-1px");
		LayoutInfoGeneral.addComponent(campoNumExp, "top:40.0px;left:0.0px;");
		
		// campoInstructor
		campoInstructor = new TextField();
		campoInstructor.setImmediate(false);
		campoInstructor.setWidth("-1px");
		campoInstructor.setHeight("-1px");
		LayoutInfoGeneral.addComponent(campoInstructor, "top:40.0px;left:350.0px;");
		
		// labelNumExp
		labelNumExp = new Label();
		labelNumExp.setImmediate(false);
		labelNumExp.setWidth("-1px");
		labelNumExp.setHeight("-1px");
		labelNumExp.setValue("Número de expediente:");
		LayoutInfoGeneral.addComponent(labelNumExp, "top:0.0px;left:0.0px;");
		
		// labelInstructor
		labelInstructor = new Label();
		labelInstructor.setImmediate(false);
		labelInstructor.setWidth("-1px");
		labelInstructor.setHeight("-1px");
		labelInstructor.setValue("Instructor:");
		LayoutInfoGeneral.addComponent(labelInstructor, "top:0.0px;left:350.0px;");
		
		// comboBoxEstado
		comboBoxEstado = new ComboBox();
		comboBoxEstado.setImmediate(false);
		comboBoxEstado.setWidth("-1px");
		comboBoxEstado.setHeight("-1px");
		LayoutInfoGeneral.addComponent(comboBoxEstado, "top:240.0px;left:-1.0px;");
		
		// comboBoxClasificacion
		comboBoxClasificacion = new ComboBox();
		comboBoxClasificacion.setImmediate(false);
		comboBoxClasificacion.setWidth("-1px");
		comboBoxClasificacion.setHeight("-1px");
		LayoutInfoGeneral.addComponent(comboBoxClasificacion, "top:240.0px;left:350.0px;");
		
		// labelAlertNumExp
		labelAlertNumExp = new Label();
		labelAlertNumExp.setImmediate(false);
		labelAlertNumExp.setWidth("-1px");
		labelAlertNumExp.setHeight("-1px");
		labelAlertNumExp.setValue("Ya existe un expediente asociado a ese número");
		LayoutInfoGeneral.addComponent(labelAlertNumExp, "top:80.0px;left:0.0px;");
		
		// labelAlertInstructor
		labelAlertInstructor = new Label();
		labelAlertInstructor.setImmediate(false);
		labelAlertInstructor.setWidth("-1px");
		labelAlertInstructor.setHeight("-1px");
		labelAlertInstructor.setValue("No se encuentra el instructor dentro del sistema");
		LayoutInfoGeneral.addComponent(labelAlertInstructor, "top:80.0px;left:350.0px;");
		
		return LayoutInfoGeneral;
	}

	@AutoGenerated
	private AbsoluteLayout buildLayoutInfoDenuncia() {
		// common part: create layout
		LayoutInfoDenuncia = new AbsoluteLayout();
		LayoutInfoDenuncia.setStyleName("vertical-scroll");
		LayoutInfoDenuncia.setImmediate(false);
		LayoutInfoDenuncia.setWidth("100.0%");
		LayoutInfoDenuncia.setHeight("100.0%");
		
		// labelFechaDenuncia
		labelFechaDenuncia = new Label();
		labelFechaDenuncia.setImmediate(false);
		labelFechaDenuncia.setWidth("-1px");
		labelFechaDenuncia.setHeight("-1px");
		labelFechaDenuncia.setValue("Fecha Denuncia:");
		LayoutInfoDenuncia.addComponent(labelFechaDenuncia, "top:0.0px;left:0.0px;");
		
		// campoFechaDenuncia
		campoFechaDenuncia = new TextField();
		campoFechaDenuncia.setImmediate(false);
		campoFechaDenuncia.setWidth("-1px");
		campoFechaDenuncia.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoFechaDenuncia, "top:40.0px;left:0.0px;");
		
		// labelParteDenunciada
		labelParteDenunciada = new Label();
		labelParteDenunciada.setImmediate(false);
		labelParteDenunciada.setWidth("-1px");
		labelParteDenunciada.setHeight("-1px");
		labelParteDenunciada.setValue("Parte Denunciada:");
		LayoutInfoDenuncia.addComponent(labelParteDenunciada, "top:0.0px;left:350.0px;");
		
		// labelCarnet
		labelCarnet = new Label();
		labelCarnet.setImmediate(false);
		labelCarnet.setWidth("-1px");
		labelCarnet.setHeight("-1px");
		labelCarnet.setValue("Carnet:");
		LayoutInfoDenuncia.addComponent(labelCarnet, "top:0.0px;left:700.0px;");
		
		// campoCarnet
		campoCarnet = new TextField();
		campoCarnet.setImmediate(false);
		campoCarnet.setWidth("-1px");
		campoCarnet.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoCarnet, "top:40.0px;left:700.0px;");
		
		// labelParteDenunciante
		labelParteDenunciante = new Label();
		labelParteDenunciante.setImmediate(false);
		labelParteDenunciante.setWidth("-1px");
		labelParteDenunciante.setHeight("-1px");
		labelParteDenunciante.setValue("Parte Denunciante:");
		LayoutInfoDenuncia.addComponent(labelParteDenunciante, "top:200.0px;left:0.0px;");
		
		// campoParteDenunciante
		campoParteDenunciante = new TextField();
		campoParteDenunciante.setImmediate(false);
		campoParteDenunciante.setWidth("-1px");
		campoParteDenunciante.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoParteDenunciante, "top:240.0px;left:0.0px;");
		
		// campoParteDenunciada
		campoParteDenunciada = new TextField();
		campoParteDenunciada.setImmediate(false);
		campoParteDenunciada.setWidth("-1px");
		campoParteDenunciada.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoParteDenunciada, "top:40.0px;left:350.0px;");
		
		// labelId
		labelId = new Label();
		labelId.setImmediate(false);
		labelId.setWidth("-1px");
		labelId.setHeight("-1px");
		labelId.setValue("Identificación:");
		LayoutInfoDenuncia.addComponent(labelId, "top:200.0px;left:350.0px;");
		
		// campoId
		campoId = new TextField();
		campoId.setImmediate(false);
		campoId.setWidth("-1px");
		campoId.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoId, "top:240.0px;left:350.0px;");
		
		// labelCausa
		labelCausa = new Label();
		labelCausa.setImmediate(false);
		labelCausa.setWidth("-1px");
		labelCausa.setHeight("-1px");
		labelCausa.setValue("Causa:");
		LayoutInfoDenuncia.addComponent(labelCausa, "top:200.0px;left:700.0px;");
		
		// campoCausa
		campoCausa = new TextField();
		campoCausa.setImmediate(false);
		campoCausa.setWidth("-1px");
		campoCausa.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoCausa, "top:240.0px;left:700.0px;");
		
		// labelArtAplicables
		labelArtAplicables = new Label();
		labelArtAplicables.setImmediate(false);
		labelArtAplicables.setWidth("-1px");
		labelArtAplicables.setHeight("-1px");
		labelArtAplicables.setValue("Artículos Aplicables:");
		LayoutInfoDenuncia.addComponent(labelArtAplicables, "top:400.0px;left:0.0px;");
		
		// campoArtAplicables
		campoArtAplicables = new TextField();
		campoArtAplicables.setImmediate(false);
		campoArtAplicables.setWidth("-1px");
		campoArtAplicables.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoArtAplicables, "top:440.0px;left:0.0px;");
		
		// labelFechaAudiencia
		labelFechaAudiencia = new Label();
		labelFechaAudiencia.setImmediate(false);
		labelFechaAudiencia.setWidth("-1px");
		labelFechaAudiencia.setHeight("-1px");
		labelFechaAudiencia.setValue("Fecha Audiencia:");
		LayoutInfoDenuncia.addComponent(labelFechaAudiencia, "top:400.0px;left:350.0px;");
		
		// campoFechaAudiencia
		campoFechaAudiencia = new TextField();
		campoFechaAudiencia.setImmediate(false);
		campoFechaAudiencia.setWidth("-1px");
		campoFechaAudiencia.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoFechaAudiencia, "top:440.0px;left:350.0px;");
		
		// labelHoraAudiencia
		labelHoraAudiencia = new Label();
		labelHoraAudiencia.setImmediate(false);
		labelHoraAudiencia.setWidth("-1px");
		labelHoraAudiencia.setHeight("-1px");
		labelHoraAudiencia.setValue("Hora Audiencia:");
		LayoutInfoDenuncia.addComponent(labelHoraAudiencia, "top:400.0px;left:700.0px;");
		
		// campoHoraAudiencia
		campoHoraAudiencia = new TextField();
		campoHoraAudiencia.setImmediate(false);
		campoHoraAudiencia.setWidth("-1px");
		campoHoraAudiencia.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoHoraAudiencia, "top:440.0px;left:700.0px;");
		
		return LayoutInfoDenuncia;
	}

	@AutoGenerated
	private AbsoluteLayout buildLayoutUbicacion() {
		// common part: create layout
		LayoutUbicacion = new AbsoluteLayout();
		LayoutUbicacion.setImmediate(false);
		LayoutUbicacion.setWidth("100.0%");
		LayoutUbicacion.setHeight("100.0%");
		
		// labelUbicacion
		labelUbicacion = new Label();
		labelUbicacion.setImmediate(false);
		labelUbicacion.setWidth("-1px");
		labelUbicacion.setHeight("-1px");
		labelUbicacion.setValue("Ubicación:");
		LayoutUbicacion.addComponent(labelUbicacion, "top:0.0px;left:0.0px;");
		
		// campoUbicacion
		campoUbicacion = new TextField();
		campoUbicacion.setImmediate(false);
		campoUbicacion.setWidth("-1px");
		campoUbicacion.setHeight("-1px");
		LayoutUbicacion.addComponent(campoUbicacion, "top:40.0px;left:0.0px;");
		
		// labelMuebleUbicacion
		labelMuebleUbicacion = new Label();
		labelMuebleUbicacion.setImmediate(false);
		labelMuebleUbicacion.setWidth("-1px");
		labelMuebleUbicacion.setHeight("-1px");
		labelMuebleUbicacion.setValue("Mueble Ubicación:");
		LayoutUbicacion.addComponent(labelMuebleUbicacion, "top:0.0px;left:350.0px;");
		
		// campoMuebleUbicacion
		campoMuebleUbicacion = new TextField();
		campoMuebleUbicacion.setImmediate(false);
		campoMuebleUbicacion.setWidth("-1px");
		campoMuebleUbicacion.setHeight("-1px");
		LayoutUbicacion.addComponent(campoMuebleUbicacion, "top:40.0px;left:350.0px;");
		
		// labelUbicLegajos
		labelUbicLegajos = new Label();
		labelUbicLegajos.setImmediate(false);
		labelUbicLegajos.setWidth("-1px");
		labelUbicLegajos.setHeight("-1px");
		labelUbicLegajos.setValue("Ubicación Legajos:");
		LayoutUbicacion.addComponent(labelUbicLegajos, "top:0.0px;left:700.0px;");
		
		// campoUbicLegajos
		campoUbicLegajos = new TextField();
		campoUbicLegajos.setImmediate(false);
		campoUbicLegajos.setWidth("-1px");
		campoUbicLegajos.setHeight("-1px");
		LayoutUbicacion.addComponent(campoUbicLegajos, "top:40.0px;left:700.0px;");
		
		// labelCantLegajos
		labelCantLegajos = new Label();
		labelCantLegajos.setImmediate(false);
		labelCantLegajos.setWidth("-1px");
		labelCantLegajos.setHeight("-1px");
		labelCantLegajos.setValue("Cantidad de Legajos:");
		LayoutUbicacion.addComponent(labelCantLegajos, "top:200.0px;left:0.0px;");
		
		// campoCantLegajos
		campoCantLegajos = new TextField();
		campoCantLegajos.setImmediate(false);
		campoCantLegajos.setWidth("-1px");
		campoCantLegajos.setHeight("-1px");
		LayoutUbicacion.addComponent(campoCantLegajos, "top:240.0px;left:0.0px;");
		
		return LayoutUbicacion;
	}

	@AutoGenerated
	private AbsoluteLayout buildLayoutFechas() {
		// common part: create layout
		LayoutFechas = new AbsoluteLayout();
		LayoutFechas.setImmediate(false);
		LayoutFechas.setWidth("100.0%");
		LayoutFechas.setHeight("100.0%");
		
		// labelFechaUltUbicacion
		labelFechaUltUbicacion = new Label();
		labelFechaUltUbicacion.setImmediate(false);
		labelFechaUltUbicacion.setWidth("-1px");
		labelFechaUltUbicacion.setHeight("-1px");
		labelFechaUltUbicacion.setValue("Fecha Última Ubicación:");
		LayoutFechas.addComponent(labelFechaUltUbicacion, "top:0.0px;left:700.0px;");
		
		// campoFechaUltUbicacion
		campoFechaUltUbicacion = new TextField();
		campoFechaUltUbicacion.setImmediate(false);
		campoFechaUltUbicacion.setWidth("-1px");
		campoFechaUltUbicacion.setHeight("-1px");
		LayoutFechas.addComponent(campoFechaUltUbicacion, "top:40.0px;left:700.0px;");
		
		// labelFechaPresentacion
		labelFechaPresentacion = new Label();
		labelFechaPresentacion.setImmediate(false);
		labelFechaPresentacion.setWidth("-1px");
		labelFechaPresentacion.setHeight("-1px");
		labelFechaPresentacion.setValue("Fecha Presentación:");
		LayoutFechas.addComponent(labelFechaPresentacion, "top:0.0px;");
		
		// campoFechaPresentacion
		campoFechaPresentacion = new TextField();
		campoFechaPresentacion.setImmediate(false);
		campoFechaPresentacion.setWidth("-1px");
		campoFechaPresentacion.setHeight("-1px");
		LayoutFechas.addComponent(campoFechaPresentacion, "top:40.0px;left:0.0px;");
		
		// labelFechaIng
		labelFechaIng = new Label();
		labelFechaIng.setImmediate(false);
		labelFechaIng.setWidth("-1px");
		labelFechaIng.setHeight("-1px");
		labelFechaIng.setValue("Fecha Ingreso Denuncia:");
		LayoutFechas.addComponent(labelFechaIng, "top:0.0px;left:350.0px;");
		
		// campoFechaIng
		campoFechaIng = new TextField();
		campoFechaIng.setImmediate(false);
		campoFechaIng.setWidth("-1px");
		campoFechaIng.setHeight("-1px");
		LayoutFechas.addComponent(campoFechaIng, "top:40.0px;left:350.0px;");
		
		// campoDuracCambioUltUbic
		campoDuracCambioUltUbic = new TextField();
		campoDuracCambioUltUbic.setImmediate(false);
		campoDuracCambioUltUbic.setWidth("-1px");
		campoDuracCambioUltUbic.setHeight("-1px");
		LayoutFechas.addComponent(campoDuracCambioUltUbic, "top:730.0px;left:0.0px;");
		
		return LayoutFechas;
	}

}
