package ucr.casoUso;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.event.ItemClickEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;

public class VistaUsuarios extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button botonCancelar;
	@AutoGenerated
	private Button botonEliminar;
	@AutoGenerated
	private Button botonInstructor;
	@AutoGenerated
	private Table tablaInstructor;
	@AutoGenerated
	private Table tablaUsuarios;
	@AutoGenerated
	private Label labelTitulo;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	
	public VistaUsuarios() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		Controlador control = Controlador.obtenerInstancia();

		// TODO add user code here
		
		tablaUsuarios.addItemClickListener(new ItemClickEvent.ItemClickListener() {
		    @Override
		    public void itemClick(ItemClickEvent itemClickEvent) {
		    	Item fila =  itemClickEvent.getItem();
		        System.out.println(   fila.getItemProperty("NombreColumna").getValue()   );
		    	
		    }
		});
		
		botonEliminar.addClickListener(new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				
			}
		});
		
		botonCancelar.addClickListener(new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				control.cambiarVista("Menu Principal");
			}
		});
	}
	
	public void llenarTabla() {
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// labelTitulo
		labelTitulo = new Label();
		labelTitulo.setStyleName("titulo");
		labelTitulo.setImmediate(false);
		labelTitulo.setWidth("-1px");
		labelTitulo.setHeight("-1px");
		labelTitulo.setValue("Usuarios del sistema");
		mainLayout.addComponent(labelTitulo, "top:20.0px;left:49.0px;");
		
		// tablaUsuarios
		tablaUsuarios = new Table();
		tablaUsuarios.setCaption("Usuarios");
		tablaUsuarios.setImmediate(false);
		tablaUsuarios.setWidth("-1px");
		tablaUsuarios.setHeight("-1px");
		mainLayout.addComponent(tablaUsuarios, "top:80.0px;left:49.0px;");
		
		// tablaInstructor
		tablaInstructor = new Table();
		tablaInstructor.setCaption("Instructores");
		tablaInstructor.setImmediate(false);
		tablaInstructor.setWidth("-1px");
		tablaInstructor.setHeight("-1px");
		mainLayout.addComponent(tablaInstructor, "top:80.0px;left:442.0px;");
		
		// botonInstructor
		botonInstructor = new Button();
		botonInstructor.setCaption("Elegir");
		botonInstructor.setImmediate(true);
		botonInstructor.setWidth("-1px");
		botonInstructor.setHeight("-1px");
		mainLayout.addComponent(botonInstructor, "top:420.0px;left:439.0px;");
		
		// botonEliminar
		botonEliminar = new Button();
		botonEliminar.setCaption("Eliminar");
		botonEliminar.setImmediate(true);
		botonEliminar.setWidth("-1px");
		botonEliminar.setHeight("-1px");
		mainLayout.addComponent(botonEliminar, "top:420.0px;left:49.0px;");
		
		// botonCancelar
		botonCancelar = new Button();
		botonCancelar.setCaption("Cancelar");
		botonCancelar.setImmediate(true);
		botonCancelar.setWidth("-1px");
		botonCancelar.setHeight("-1px");
		mainLayout.addComponent(botonCancelar, "top:420.0px;left:135.0px;");
		
		return mainLayout;
	}
}
