package ucr.casoUso;

import java.util.HashMap;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;

public class VistaExpediente extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button botonRechazar;
	@AutoGenerated
	private Button botonAceptar;
	@AutoGenerated
	private Label labelConfirmacion;
	@AutoGenerated
	private Label valorNumExpediente;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_4;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_3;
	@AutoGenerated
	private Button botonEnvPlazo;
	@AutoGenerated
	private TextField campoPlazo;
	@AutoGenerated
	private Button botonModPlazo;
	@AutoGenerated
	private Label valorPlazo;
	@AutoGenerated
	private Label labelPlazo;
	@AutoGenerated
	private Button botonEnvEstado;
	@AutoGenerated
	private Button botonEnvClas;
	@AutoGenerated
	private TextField campoClas;
	@AutoGenerated
	private TextField campoEstado;
	@AutoGenerated
	private Button botonModClas;
	@AutoGenerated
	private Label valorClas;
	@AutoGenerated
	private Label labelClas;
	@AutoGenerated
	private Button botonModEstado;
	@AutoGenerated
	private Label valorEstado;
	@AutoGenerated
	private Label labelEstado;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_2;
	@AutoGenerated
	private Label valorParteDenunciante;
	@AutoGenerated
	private Label labelParteDenunciante;
	@AutoGenerated
	private Label valorCarnet;
	@AutoGenerated
	private Label labelCarnet;
	@AutoGenerated
	private Label valorParteDenunciada;
	@AutoGenerated
	private Label labelParteDenunciada;
	@AutoGenerated
	private Label valorFechaIng;
	@AutoGenerated
	private Label labelFechaIng;
	@AutoGenerated
	private Label valorInst;
	@AutoGenerated
	private Label labelInst;
	@AutoGenerated
	private Button botonVolver;
	@AutoGenerated
	private Button botonArchivar;
	@AutoGenerated
	private Button botonLog;
	@AutoGenerated
	private Label labelNumExpediente;
	private ControladorExpediente controlador;
	private Controlador control;
	private HashMap<String, String> datosExpediente;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public VistaExpediente() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		controlador = ControladorExpediente.obtenerInstancia();
		control = Controlador.obtenerInstancia();
		
		//Pedir los datos del expediente
		datosExpediente = controlador.obtenerDatos();
		
		//Ocultar los campos de modificación
		desaparecerCampos();
		
		//Inactivar la modificación del expediente si está archivado o si no se tiene permisos de modificación
		if (control.getTipoUsuario() != "Instructor" && control.getTipoUsuario() != "Asistente"){
			
			//desaparecerBotones();
		}
		else if (control.getNumInstructor() != datosExpediente.get("Instructor Asignado")) {
			
			//desaparecerBotones();
		}
		else if (datosExpediente.get("Archivado").compareTo("t") == 0) {
			
			desaparecerBotones();
		}
		
		valorNumExpediente.setValue(datosExpediente.get("Numero Expediente"));
		valorInst.setValue(datosExpediente.get("Instructor Asignado"));
		valorClas.setValue(datosExpediente.get("Clasificacion"));
		
		botonArchivar.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				botonAceptar.setVisible(true);
				botonRechazar.setVisible(true);
				labelConfirmacion.setVisible(true);
			}
			
		});
		
		botonAceptar.addClickListener(new ClickListener () {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				//controlador.enviarDatos("true", "archivado");
				control.cambiarVista("Expediente", datosExpediente.get("Codigo"));
			}
			
		});
		
		botonRechazar.addClickListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				botonAceptar.setVisible(false);
				botonRechazar.setVisible(false);
				labelConfirmacion.setVisible(false);
			}
			
		});
		
		botonLog.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				control.cambiarVista("Logs", datosExpediente.get("Codigo"));
			}
			
		});
	
		botonVolver.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				if (datosExpediente.get("Archivado") == "true") {
					//control.cambiarVista("Lista Expedientes Archivados");
				} else {
					control.cambiarVista("Lista Expedientes");
				}
			}
			
		});
		
		botonModClas.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				desaparecerCampos();
				campoClas.setVisible(true);
				botonEnvClas.setVisible(true);
				
			}
			
		});
		
		botonEnvClas.addClickListener(new ClickListener () {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				// if datos válidos
					String datoViejo = labelClas.getValue();
					String nuevoDato = campoClas.getValue();
					controlador.enviarDatos(nuevoDato, "clasificacion", datosExpediente.get("Instructor Asignado"), datosExpediente.get("Numero Expediente"), datoViejo, "1");
					control.cambiarVista("Expediente", datosExpediente.get("Codigo"));
			}
			
		});
		
		botonModEstado.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				desaparecerCampos();
				campoEstado.setVisible(true);
				botonEnvEstado.setVisible(true);
				
			}
			
		});
		
		botonEnvEstado.addClickListener(new ClickListener () {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				// if datos válidos
					//String nuevoDato = campoEstado.getValue();
					//controlador.enviarDatos(nuevoDato, "estado");
					//control.cambiarVista("Expediente", datosExpediente.get("Codigo"));
			}
			
		});
	}
	
	private void desaparecerCampos() {
		
		botonAceptar.setVisible(false);
		botonRechazar.setVisible(false);
		labelConfirmacion.setVisible(false);
		
		campoClas.setVisible(false);
		botonEnvClas.setVisible(false);
		campoEstado.setVisible(false);
		botonEnvEstado.setVisible(false);
		
	}
	
	private void desaparecerBotones() {
		
		botonModEstado.setVisible(false);
		botonModClas.setVisible(false);

		botonArchivar.setVisible(false);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("1500px");
		mainLayout.setHeight("1500px");
		
		// top-level component properties
		setWidth("1500px");
		setHeight("1500px");
		
		// labelNumExpediente
		labelNumExpediente = new Label();
		labelNumExpediente.setStyleName("titulo");
		labelNumExpediente.setImmediate(false);
		labelNumExpediente.setWidth("-1px");
		labelNumExpediente.setHeight("-1px");
		labelNumExpediente.setValue("Expediente");
		mainLayout.addComponent(labelNumExpediente, "top:60.0px;left:60.0px;");
		
		// botonLog
		botonLog = new Button();
		botonLog.setCaption("Registro");
		botonLog.setImmediate(true);
		botonLog.setWidth("-1px");
		botonLog.setHeight("-1px");
		mainLayout.addComponent(botonLog, "top:60.0px;left:850.0px;");
		
		// botonArchivar
		botonArchivar = new Button();
		botonArchivar.setCaption("Archivar");
		botonArchivar.setImmediate(true);
		botonArchivar.setWidth("-1px");
		botonArchivar.setHeight("-1px");
		mainLayout.addComponent(botonArchivar, "top:60.0px;left:700.0px;");
		
		// botonVolver
		botonVolver = new Button();
		botonVolver.setCaption("Volver");
		botonVolver.setImmediate(true);
		botonVolver.setWidth("-1px");
		botonVolver.setHeight("-1px");
		mainLayout.addComponent(botonVolver, "top:60.0px;left:1000.0px;");
		
		// labelInst
		labelInst = new Label();
		labelInst.setImmediate(false);
		labelInst.setWidth("-1px");
		labelInst.setHeight("-1px");
		labelInst.setValue("Instructor Asignado:");
		mainLayout.addComponent(labelInst, "top:150.0px;left:60.0px;");
		
		// valorInst
		valorInst = new Label();
		valorInst.setImmediate(false);
		valorInst.setWidth("-1px");
		valorInst.setHeight("-1px");
		valorInst.setValue("Label");
		mainLayout.addComponent(valorInst, "top:150.0px;left:231.0px;");
		
		// absoluteLayout_2
		absoluteLayout_2 = buildAbsoluteLayout_2();
		mainLayout.addComponent(absoluteLayout_2, "top:240.0px;left:410.0px;");
		
		// absoluteLayout_3
		absoluteLayout_3 = buildAbsoluteLayout_3();
		mainLayout.addComponent(absoluteLayout_3, "top:240.0px;left:60.0px;");
		
		// absoluteLayout_4
		absoluteLayout_4 = new AbsoluteLayout();
		absoluteLayout_4.setImmediate(false);
		absoluteLayout_4.setWidth("250px");
		absoluteLayout_4.setHeight("238px");
		mainLayout.addComponent(absoluteLayout_4, "top:240.0px;left:710.0px;");
		
		// valorNumExpediente
		valorNumExpediente = new Label();
		valorNumExpediente.setImmediate(false);
		valorNumExpediente.setWidth("-1px");
		valorNumExpediente.setHeight("-1px");
		valorNumExpediente.setValue("Label");
		mainLayout.addComponent(valorNumExpediente, "top:60.0px;left:160.0px;");
		
		// labelConfirmacion
		labelConfirmacion = new Label();
		labelConfirmacion.setImmediate(false);
		labelConfirmacion.setWidth("-1px");
		labelConfirmacion.setHeight("-1px");
		labelConfirmacion.setValue("¿Está seguro que desea archivar el expediente?");
		mainLayout.addComponent(labelConfirmacion, "top:150.0px;left:569.0px;");
		
		// botonAceptar
		botonAceptar = new Button();
		botonAceptar.setCaption("Sí");
		botonAceptar.setImmediate(true);
		botonAceptar.setWidth("-1px");
		botonAceptar.setHeight("-1px");
		mainLayout.addComponent(botonAceptar, "top:142.0px;left:950.0px;");
		
		// botonRechazar
		botonRechazar = new Button();
		botonRechazar.setCaption("No");
		botonRechazar.setImmediate(true);
		botonRechazar.setWidth("-1px");
		botonRechazar.setHeight("-1px");
		mainLayout.addComponent(botonRechazar, "top:142.0px;left:1020.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_2() {
		// common part: create layout
		absoluteLayout_2 = new AbsoluteLayout();
		absoluteLayout_2.setImmediate(false);
		absoluteLayout_2.setWidth("250px");
		absoluteLayout_2.setHeight("735px");
		
		// labelFechaIng
		labelFechaIng = new Label();
		labelFechaIng.setImmediate(false);
		labelFechaIng.setWidth("-1px");
		labelFechaIng.setHeight("-1px");
		labelFechaIng.setValue("Fecha Ingreso Denuncia:");
		absoluteLayout_2.addComponent(labelFechaIng, "top:0.0px;left:0.0px;");
		
		// valorFechaIng
		valorFechaIng = new Label();
		valorFechaIng.setImmediate(false);
		valorFechaIng.setWidth("-1px");
		valorFechaIng.setHeight("-1px");
		valorFechaIng.setValue("Label");
		absoluteLayout_2.addComponent(valorFechaIng, "top:40.0px;left:0.0px;");
		
		// labelParteDenunciada
		labelParteDenunciada = new Label();
		labelParteDenunciada.setImmediate(false);
		labelParteDenunciada.setWidth("-1px");
		labelParteDenunciada.setHeight("-1px");
		labelParteDenunciada.setValue("Parte Denunciada:");
		absoluteLayout_2.addComponent(labelParteDenunciada, "top:200.0px;left:1.0px;");
		
		// valorParteDenunciada
		valorParteDenunciada = new Label();
		valorParteDenunciada.setImmediate(false);
		valorParteDenunciada.setWidth("-1px");
		valorParteDenunciada.setHeight("-1px");
		valorParteDenunciada.setValue("Label");
		absoluteLayout_2.addComponent(valorParteDenunciada, "top:240.0px;left:0.0px;");
		
		// labelCarnet
		labelCarnet = new Label();
		labelCarnet.setImmediate(false);
		labelCarnet.setWidth("-1px");
		labelCarnet.setHeight("-1px");
		labelCarnet.setValue("Carnet:");
		absoluteLayout_2.addComponent(labelCarnet, "top:400.0px;left:0.0px;");
		
		// valorCarnet
		valorCarnet = new Label();
		valorCarnet.setImmediate(false);
		valorCarnet.setWidth("-1px");
		valorCarnet.setHeight("-1px");
		valorCarnet.setValue("Label");
		absoluteLayout_2.addComponent(valorCarnet, "top:440.0px;left:0.0px;");
		
		// labelParteDenunciante
		labelParteDenunciante = new Label();
		labelParteDenunciante.setImmediate(false);
		labelParteDenunciante.setWidth("-1px");
		labelParteDenunciante.setHeight("-1px");
		labelParteDenunciante.setValue("Parte Denunciante:");
		absoluteLayout_2.addComponent(labelParteDenunciante, "top:600.0px;left:0.0px;");
		
		// valorParteDenunciante
		valorParteDenunciante = new Label();
		valorParteDenunciante.setImmediate(false);
		valorParteDenunciante.setWidth("-1px");
		valorParteDenunciante.setHeight("-1px");
		valorParteDenunciante.setValue("Label");
		absoluteLayout_2.addComponent(valorParteDenunciante, "top:640.0px;left:0.0px;");
		
		return absoluteLayout_2;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_3() {
		// common part: create layout
		absoluteLayout_3 = new AbsoluteLayout();
		absoluteLayout_3.setImmediate(false);
		absoluteLayout_3.setWidth("250px");
		absoluteLayout_3.setHeight("735px");
		
		// labelEstado
		labelEstado = new Label();
		labelEstado.setImmediate(false);
		labelEstado.setWidth("-1px");
		labelEstado.setHeight("-1px");
		labelEstado.setValue("Estado: ");
		absoluteLayout_3.addComponent(labelEstado, "top:0.0px;left:0.0px;");
		
		// valorEstado
		valorEstado = new Label();
		valorEstado.setImmediate(false);
		valorEstado.setWidth("-1px");
		valorEstado.setHeight("-1px");
		valorEstado.setValue("Label");
		absoluteLayout_3.addComponent(valorEstado, "top:40.0px;left:0.0px;");
		
		// botonModEstado
		botonModEstado = new Button();
		botonModEstado.setCaption("Modificar");
		botonModEstado.setImmediate(true);
		botonModEstado.setWidth("-1px");
		botonModEstado.setHeight("-1px");
		absoluteLayout_3.addComponent(botonModEstado, "top:80.0px;left:1.0px;");
		
		// labelClas
		labelClas = new Label();
		labelClas.setImmediate(false);
		labelClas.setWidth("-1px");
		labelClas.setHeight("-1px");
		labelClas.setValue("Clasificación:");
		absoluteLayout_3.addComponent(labelClas, "top:200.0px;left:0.0px;");
		
		// valorClas
		valorClas = new Label();
		valorClas.setImmediate(false);
		valorClas.setWidth("-1px");
		valorClas.setHeight("-1px");
		valorClas.setValue("Label");
		absoluteLayout_3.addComponent(valorClas, "top:240.0px;left:0.0px;");
		
		// botonModClas
		botonModClas = new Button();
		botonModClas.setCaption("Modificar");
		botonModClas.setImmediate(true);
		botonModClas.setWidth("-1px");
		botonModClas.setHeight("-1px");
		absoluteLayout_3.addComponent(botonModClas, "top:280.0px;left:0.0px;");
		
		// campoEstado
		campoEstado = new TextField();
		campoEstado.setImmediate(false);
		campoEstado.setWidth("-1px");
		campoEstado.setHeight("-1px");
		absoluteLayout_3.addComponent(campoEstado, "top:130.0px;left:0.0px;");
		
		// campoClas
		campoClas = new TextField();
		campoClas.setImmediate(false);
		campoClas.setWidth("-1px");
		campoClas.setHeight("-1px");
		absoluteLayout_3.addComponent(campoClas, "top:330.0px;left:0.0px;");
		
		// botonEnvClas
		botonEnvClas = new Button();
		botonEnvClas.setCaption("M");
		botonEnvClas.setImmediate(true);
		botonEnvClas.setWidth("-1px");
		botonEnvClas.setHeight("-1px");
		absoluteLayout_3.addComponent(botonEnvClas, "top:330.0px;left:200.0px;");
		
		// botonEnvEstado
		botonEnvEstado = new Button();
		botonEnvEstado.setCaption("M");
		botonEnvEstado.setImmediate(true);
		botonEnvEstado.setWidth("-1px");
		botonEnvEstado.setHeight("-1px");
		absoluteLayout_3.addComponent(botonEnvEstado, "top:130.0px;left:200.0px;");
		
		// labelPlazo
		labelPlazo = new Label();
		labelPlazo.setImmediate(false);
		labelPlazo.setWidth("-1px");
		labelPlazo.setHeight("-1px");
		labelPlazo.setValue("Plazo Meta:");
		absoluteLayout_3.addComponent(labelPlazo, "top:400.0px;left:0.0px;");
		
		// valorPlazo
		valorPlazo = new Label();
		valorPlazo.setImmediate(false);
		valorPlazo.setWidth("-1px");
		valorPlazo.setHeight("-1px");
		valorPlazo.setValue("Label");
		absoluteLayout_3.addComponent(valorPlazo, "top:440.0px;left:0.0px;");
		
		// botonModPlazo
		botonModPlazo = new Button();
		botonModPlazo.setCaption("Modificar");
		botonModPlazo.setImmediate(true);
		botonModPlazo.setWidth("-1px");
		botonModPlazo.setHeight("-1px");
		absoluteLayout_3.addComponent(botonModPlazo, "top:480.0px;left:1.0px;");
		
		// campoPlazo
		campoPlazo = new TextField();
		campoPlazo.setImmediate(false);
		campoPlazo.setWidth("-1px");
		campoPlazo.setHeight("-1px");
		absoluteLayout_3.addComponent(campoPlazo, "top:530.0px;left:0.0px;");
		
		// botonEnvPlazo
		botonEnvPlazo = new Button();
		botonEnvPlazo.setCaption("M");
		botonEnvPlazo.setImmediate(true);
		botonEnvPlazo.setWidth("-1px");
		botonEnvPlazo.setHeight("-1px");
		absoluteLayout_3.addComponent(botonEnvPlazo, "top:530.0px;left:200.0px;");
		
		return absoluteLayout_3;
	}

}
