package ucr.casoUso;

import java.util.HashMap;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.FieldEvents.TextChangeEvent;
import com.vaadin.event.FieldEvents.TextChangeListener;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;

public class VistaCrearExpediente extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Accordion Acordeon;
	@AutoGenerated
	private AbsoluteLayout LayoutFechas;
	@AutoGenerated
	private TextField campoDuracCambioUltUbic;
	@AutoGenerated
	private TextField campoFechaIng;
	@AutoGenerated
	private Label labelFechaIng;
	@AutoGenerated
	private TextField campoFechaPresentacion;
	@AutoGenerated
	private Label labelFechaPresentacion;
	@AutoGenerated
	private TextField campoFechaUltUbicacion;
	@AutoGenerated
	private Label labelFechaUltUbicacion;
	@AutoGenerated
	private AbsoluteLayout LayoutUbicacion;
	@AutoGenerated
	private TextField campoCantLegajos;
	@AutoGenerated
	private Label labelCantLegajos;
	@AutoGenerated
	private TextField campoUbicLegajos;
	@AutoGenerated
	private Label labelUbicLegajos;
	@AutoGenerated
	private TextField campoMuebleUbicacion;
	@AutoGenerated
	private Label labelMuebleUbicacion;
	@AutoGenerated
	private TextField campoUbicacion;
	@AutoGenerated
	private Label labelUbicacion;
	@AutoGenerated
	private AbsoluteLayout LayoutInfoDenuncia;
	@AutoGenerated
	private TextField campoHoraAudiencia;
	@AutoGenerated
	private Label labelHoraAudiencia;
	@AutoGenerated
	private TextField campoFechaAudiencia;
	@AutoGenerated
	private Label labelFechaAudiencia;
	@AutoGenerated
	private TextField campoArtAplicables;
	@AutoGenerated
	private Label labelArtAplicables;
	@AutoGenerated
	private TextField campoCausa;
	@AutoGenerated
	private Label labelCausa;
	@AutoGenerated
	private TextField campoId;
	@AutoGenerated
	private Label labelId;
	@AutoGenerated
	private TextField campoParteDenunciada;
	@AutoGenerated
	private TextField campoParteDenunciante;
	@AutoGenerated
	private Label labelParteDenunciante;
	@AutoGenerated
	private TextField campoCarnet;
	@AutoGenerated
	private Label labelCarnet;
	@AutoGenerated
	private Label labelParteDenunciada;
	@AutoGenerated
	private TextField campoFechaDenuncia;
	@AutoGenerated
	private Label labelFechaDenuncia;
	@AutoGenerated
	private AbsoluteLayout LayoutInfoGeneral;
	@AutoGenerated
	private Label labelInstructor;
	@AutoGenerated
	private Label labelNumExp;
	@AutoGenerated
	private TextField campoInstructor;
	@AutoGenerated
	private TextField campoNumExp;
	@AutoGenerated
	private TextField campoResponsable;
	@AutoGenerated
	private Label labelResponsable;
	@AutoGenerated
	private Label labelEstado;
	@AutoGenerated
	private TextField campoClas;
	@AutoGenerated
	private TextField campoEstado;
	@AutoGenerated
	private Label labelClas;
	@AutoGenerated
	private Button botonRechazar;
	@AutoGenerated
	private Button botonAceptar;
	@AutoGenerated
	private Label labelConfirmacion;
	@AutoGenerated
	private Label valorNumExpediente;
	@AutoGenerated
	private Label valorInst;
	@AutoGenerated
	private Label labelInst;
	@AutoGenerated
	private Button botonVolver;
	@AutoGenerated
	private Label labelNumExpediente;
	private ControladorCrearExpediente controlador;
	private Controlador control;
	private HashMap<String, String> datosExpediente;
	private String valorNumExp;
	private String valorInstructor;
	private String valorResponsable;
	private String valorEstado;
	private String valorClasificacion;
	
	private String valorFechaDenuncia;
	private String valorParteDenunciada;
	private String valorCarneDenunciada;
	private String valorParteDenunciante;
	private String valorIdentDenunciante;
	private String valorCausaDenun;
	private String valorArtAplicables;
	private String valorFechaAudiencia;
	private String valorHoraAudiencia;
	
	private String valorUbicacion;
	private String valorMuebleUbi;
	private String valorUbiLegajos;
	private String valorCantidadLegajos;
	
	private String valorFechaPresentacion;
	private String valorFechaIngrDenun;
	private String valorFechaUltimaUbi;
	
	
	
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public VistaCrearExpediente() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		//Campos de "Informacion General"
		
		campoNumExp.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorNumExp = campoNumExp.getValue();
            	//No repetido
            }
		});
		
		campoInstructor.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorInstructor = campoInstructor.getValue();
            	//Revisar que existe
            }
		});
		
		campoResponsable.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorResponsable = campoResponsable.getValue();
            }
		});
		
		
		//Campos de "Informacion de Denuncia"
		
		campoFechaDenuncia.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorFechaDenuncia = campoFechaDenuncia.getValue();
            }
		});
		
		campoParteDenunciada.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorParteDenunciada = campoParteDenunciada.getValue();
            }
		});
		
		campoCarnet.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorCarneDenunciada = campoCarnet.getValue();
            }
		});
		
		campoParteDenunciante.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorParteDenunciante = campoParteDenunciante.getValue();
            }
		});
		
		campoId.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorIdentDenunciante = campoId.getValue();
            }
		});
		
		campoCausa.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorCausaDenun = campoCausa.getValue();
            }
		});
		
		campoArtAplicables.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorArtAplicables = campoArtAplicables.getValue();
            }
		});
		
		campoFechaAudiencia.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorFechaAudiencia = campoFechaAudiencia.getValue();
            }
		});
		
		campoHoraAudiencia.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorHoraAudiencia = campoHoraAudiencia.getValue();
            }
		});
		
		//Campos de Ubicacion
		
		campoUbicacion.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorUbicacion = campoUbicacion.getValue();
            }
		});
		
		campoMuebleUbicacion.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorMuebleUbi = campoMuebleUbicacion.getValue();
            }
		});
		
		campoUbicLegajos.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorUbiLegajos = campoUbicLegajos.getValue();
            }
		});
		
		campoCantLegajos.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorCantidadLegajos = campoCantLegajos.getValue();
            }
		});

		//Campos de Fechas
		
		campoFechaPresentacion.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorFechaPresentacion = campoFechaPresentacion.getValue();
            }
		});
		
		campoFechaIng.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorFechaIngrDenun = campoFechaIng.getValue();
            }
		});
		
		campoFechaUltUbicacion.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	valorFechaUltimaUbi = campoFechaUltUbicacion.getValue();
            }
		});
		
	/*	
		botonRechazar.addClickListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				botonAceptar.setVisible(false);
				botonRechazar.setVisible(false);
				labelConfirmacion.setVisible(false);
			}
			
		});
	
		botonVolver.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				if (datosExpediente.get("Archivado") == "true") {
					//control.cambiarVista("Lista Expedientes Archivados");
				} else {
					control.cambiarVista("Lista Expedientes");
				}
			}
			
		});*/
		
	}
	
	/*
	private void desaparecerCampos() {
		
		botonAceptar.setVisible(false);
		botonRechazar.setVisible(false);
		labelConfirmacion.setVisible(false);
		campoEstado.setVisible(false);
		campoClas.setVisible(false);
		campoResponsable.setVisible(false);
		campoFechaDenuncia.setVisible(false);

		campoParteDenunciada.setVisible(false);
	
		campoCarnet.setVisible(false);
	
		campoParteDenunciante.setVisible(false);

		campoId.setVisible(false);

		campoCausa.setVisible(false);

		campoArtAplicables.setVisible(false);

		campoFechaAudiencia.setVisible(false);

		campoHoraAudiencia.setVisible(false);

		campoUbicacion.setVisible(false);
		campoMuebleUbicacion.setVisible(false);
		campoUbicLegajos.setVisible(false);
		campoCantLegajos.setVisible(false);
		campoFechaPresentacion.setVisible(false);
		campoFechaIng.setVisible(false);
		
		campoDuracPresentacionIngreso.setVisible(false);
		
		campoFechaCambioEstado.setVisible(false);
	
		campoPlazoIngresoCambio.setVisible(false);
		campoDuracIngresoCambio.setVisible(false);
		
		campoFechaUltUbicacion.setVisible(false);
		
		campoPlazoIngresoUltUbic.setVisible(false);
		
		campoDuracIngresoUltUbic.setVisible(false);
		
		campoDuracCambioUltUbic.setVisible(false);
		
	
	}*/
	
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// labelNumExpediente
		labelNumExpediente = new Label();
		labelNumExpediente.setStyleName("titulo");
		labelNumExpediente.setImmediate(false);
		labelNumExpediente.setWidth("-1px");
		labelNumExpediente.setHeight("-1px");
		labelNumExpediente.setValue("Expediente");
		mainLayout.addComponent(labelNumExpediente, "top:60.0px;left:60.0px;");
		
		// botonVolver
		botonVolver = new Button();
		botonVolver.setCaption("Volver");
		botonVolver.setImmediate(true);
		botonVolver.setWidth("-1px");
		botonVolver.setHeight("-1px");
		mainLayout.addComponent(botonVolver, "top:60.0px;left:1000.0px;");
		
		// labelInst
		labelInst = new Label();
		labelInst.setStyleName("error");
		labelInst.setImmediate(false);
		labelInst.setWidth("-1px");
		labelInst.setHeight("-1px");
		labelInst.setValue("Instructor Asignado:");
		mainLayout.addComponent(labelInst, "top:150.0px;left:60.0px;");
		
		// valorInst
		valorInst = new Label();
		valorInst.setImmediate(false);
		valorInst.setWidth("-1px");
		valorInst.setHeight("-1px");
		valorInst.setValue("Label");
		mainLayout.addComponent(valorInst, "top:150.0px;left:231.0px;");
		
		// valorNumExpediente
		valorNumExpediente = new Label();
		valorNumExpediente.setImmediate(false);
		valorNumExpediente.setWidth("-1px");
		valorNumExpediente.setHeight("-1px");
		valorNumExpediente.setValue("Label");
		mainLayout.addComponent(valorNumExpediente, "top:60.0px;left:160.0px;");
		
		// labelConfirmacion
		labelConfirmacion = new Label();
		labelConfirmacion.setImmediate(false);
		labelConfirmacion.setWidth("-1px");
		labelConfirmacion.setHeight("-1px");
		labelConfirmacion.setValue("¿Está seguro que desea ingresar el expediente?");
		mainLayout.addComponent(labelConfirmacion, "top:150.0px;left:569.0px;");
		
		// botonAceptar
		botonAceptar = new Button();
		botonAceptar.setCaption("Sí");
		botonAceptar.setImmediate(true);
		botonAceptar.setWidth("-1px");
		botonAceptar.setHeight("-1px");
		mainLayout.addComponent(botonAceptar, "top:142.0px;left:950.0px;");
		
		// botonRechazar
		botonRechazar = new Button();
		botonRechazar.setCaption("No");
		botonRechazar.setImmediate(true);
		botonRechazar.setWidth("-1px");
		botonRechazar.setHeight("-1px");
		mainLayout.addComponent(botonRechazar, "top:142.0px;left:1020.0px;");
		
		// Acordeon
		Acordeon = buildAcordeon();
		mainLayout.addComponent(Acordeon, "top:240.0px;left:60.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private Accordion buildAcordeon() {
		// common part: create layout
		Acordeon = new Accordion();
		Acordeon.setImmediate(true);
		Acordeon.setWidth("90.0%");
		Acordeon.setHeight("90.0%");
		
		// LayoutInfoGeneral
		LayoutInfoGeneral = buildLayoutInfoGeneral();
		Acordeon.addTab(LayoutInfoGeneral, "Información General", null);
		
		// LayoutInfoDenuncia
		LayoutInfoDenuncia = buildLayoutInfoDenuncia();
		Acordeon.addTab(LayoutInfoDenuncia, "Información de la Denuncia", null);
		
		// LayoutUbicacion
		LayoutUbicacion = buildLayoutUbicacion();
		Acordeon.addTab(LayoutUbicacion, "Ubicación", null);
		
		// LayoutFechas
		LayoutFechas = buildLayoutFechas();
		Acordeon.addTab(LayoutFechas, "Fechas", null);
		
		return Acordeon;
	}

	@AutoGenerated
	private AbsoluteLayout buildLayoutInfoGeneral() {
		// common part: create layout
		LayoutInfoGeneral = new AbsoluteLayout();
		LayoutInfoGeneral.setImmediate(false);
		LayoutInfoGeneral.setWidth("100.0%");
		LayoutInfoGeneral.setHeight("100.0%");
		
		// labelClas
		labelClas = new Label();
		labelClas.setImmediate(false);
		labelClas.setWidth("-1px");
		labelClas.setHeight("-1px");
		labelClas.setValue("Clasificación:");
		LayoutInfoGeneral.addComponent(labelClas, "top:200.0px;left:350.0px;");
		
		// campoEstado
		campoEstado = new TextField();
		campoEstado.setImmediate(false);
		campoEstado.setWidth("-1px");
		campoEstado.setHeight("-1px");
		LayoutInfoGeneral.addComponent(campoEstado, "top:240.0px;left:0.0px;");
		
		// campoClas
		campoClas = new TextField();
		campoClas.setImmediate(false);
		campoClas.setWidth("-1px");
		campoClas.setHeight("-1px");
		LayoutInfoGeneral.addComponent(campoClas, "top:240.0px;left:350.0px;");
		
		// labelEstado
		labelEstado = new Label();
		labelEstado.setImmediate(false);
		labelEstado.setWidth("-1px");
		labelEstado.setHeight("-1px");
		labelEstado.setValue("Estado: ");
		LayoutInfoGeneral.addComponent(labelEstado, "top:200.0px;left:0.0px;");
		
		// labelResponsable
		labelResponsable = new Label();
		labelResponsable.setImmediate(false);
		labelResponsable.setWidth("-1px");
		labelResponsable.setHeight("-1px");
		labelResponsable.setValue("Responsable:");
		LayoutInfoGeneral.addComponent(labelResponsable, "top:0.0px;left:700.0px;");
		
		// campoResponsable
		campoResponsable = new TextField();
		campoResponsable.setImmediate(false);
		campoResponsable.setWidth("-1px");
		campoResponsable.setHeight("-1px");
		LayoutInfoGeneral.addComponent(campoResponsable, "top:40.0px;left:700.0px;");
		
		// campoNumExp
		campoNumExp = new TextField();
		campoNumExp.setImmediate(false);
		campoNumExp.setWidth("-1px");
		campoNumExp.setHeight("-1px");
		LayoutInfoGeneral.addComponent(campoNumExp, "top:40.0px;left:0.0px;");
		
		// campoInstructor
		campoInstructor = new TextField();
		campoInstructor.setImmediate(false);
		campoInstructor.setWidth("-1px");
		campoInstructor.setHeight("-1px");
		LayoutInfoGeneral.addComponent(campoInstructor, "top:40.0px;left:350.0px;");
		
		// labelNumExp
		labelNumExp = new Label();
		labelNumExp.setImmediate(false);
		labelNumExp.setWidth("-1px");
		labelNumExp.setHeight("-1px");
		labelNumExp.setValue("Número de expediente:");
		LayoutInfoGeneral.addComponent(labelNumExp, "top:0.0px;left:0.0px;");
		
		// labelInstructor
		labelInstructor = new Label();
		labelInstructor.setImmediate(false);
		labelInstructor.setWidth("-1px");
		labelInstructor.setHeight("-1px");
		labelInstructor.setValue("Instructor:");
		LayoutInfoGeneral.addComponent(labelInstructor, "top:0.0px;left:350.0px;");
		
		return LayoutInfoGeneral;
	}

	@AutoGenerated
	private AbsoluteLayout buildLayoutInfoDenuncia() {
		// common part: create layout
		LayoutInfoDenuncia = new AbsoluteLayout();
		LayoutInfoDenuncia.setStyleName("vertical-scroll");
		LayoutInfoDenuncia.setImmediate(false);
		LayoutInfoDenuncia.setWidth("100.0%");
		LayoutInfoDenuncia.setHeight("100.0%");
		
		// labelFechaDenuncia
		labelFechaDenuncia = new Label();
		labelFechaDenuncia.setImmediate(false);
		labelFechaDenuncia.setWidth("-1px");
		labelFechaDenuncia.setHeight("-1px");
		labelFechaDenuncia.setValue("Fecha Denuncia:");
		LayoutInfoDenuncia.addComponent(labelFechaDenuncia, "top:0.0px;left:0.0px;");
		
		// campoFechaDenuncia
		campoFechaDenuncia = new TextField();
		campoFechaDenuncia.setImmediate(false);
		campoFechaDenuncia.setWidth("-1px");
		campoFechaDenuncia.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoFechaDenuncia, "top:40.0px;left:0.0px;");
		
		// labelParteDenunciada
		labelParteDenunciada = new Label();
		labelParteDenunciada.setImmediate(false);
		labelParteDenunciada.setWidth("-1px");
		labelParteDenunciada.setHeight("-1px");
		labelParteDenunciada.setValue("Parte Denunciada:");
		LayoutInfoDenuncia.addComponent(labelParteDenunciada, "top:0.0px;left:350.0px;");
		
		// labelCarnet
		labelCarnet = new Label();
		labelCarnet.setImmediate(false);
		labelCarnet.setWidth("-1px");
		labelCarnet.setHeight("-1px");
		labelCarnet.setValue("Carnet:");
		LayoutInfoDenuncia.addComponent(labelCarnet, "top:0.0px;left:700.0px;");
		
		// campoCarnet
		campoCarnet = new TextField();
		campoCarnet.setImmediate(false);
		campoCarnet.setWidth("-1px");
		campoCarnet.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoCarnet, "top:40.0px;left:700.0px;");
		
		// labelParteDenunciante
		labelParteDenunciante = new Label();
		labelParteDenunciante.setImmediate(false);
		labelParteDenunciante.setWidth("-1px");
		labelParteDenunciante.setHeight("-1px");
		labelParteDenunciante.setValue("Parte Denunciante:");
		LayoutInfoDenuncia.addComponent(labelParteDenunciante, "top:200.0px;left:0.0px;");
		
		// campoParteDenunciante
		campoParteDenunciante = new TextField();
		campoParteDenunciante.setImmediate(false);
		campoParteDenunciante.setWidth("-1px");
		campoParteDenunciante.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoParteDenunciante, "top:240.0px;left:0.0px;");
		
		// campoParteDenunciada
		campoParteDenunciada = new TextField();
		campoParteDenunciada.setImmediate(false);
		campoParteDenunciada.setWidth("-1px");
		campoParteDenunciada.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoParteDenunciada, "top:40.0px;left:350.0px;");
		
		// labelId
		labelId = new Label();
		labelId.setImmediate(false);
		labelId.setWidth("-1px");
		labelId.setHeight("-1px");
		labelId.setValue("Identificación:");
		LayoutInfoDenuncia.addComponent(labelId, "top:200.0px;left:350.0px;");
		
		// campoId
		campoId = new TextField();
		campoId.setImmediate(false);
		campoId.setWidth("-1px");
		campoId.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoId, "top:240.0px;left:350.0px;");
		
		// labelCausa
		labelCausa = new Label();
		labelCausa.setImmediate(false);
		labelCausa.setWidth("-1px");
		labelCausa.setHeight("-1px");
		labelCausa.setValue("Causa:");
		LayoutInfoDenuncia.addComponent(labelCausa, "top:200.0px;left:700.0px;");
		
		// campoCausa
		campoCausa = new TextField();
		campoCausa.setImmediate(false);
		campoCausa.setWidth("-1px");
		campoCausa.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoCausa, "top:240.0px;left:700.0px;");
		
		// labelArtAplicables
		labelArtAplicables = new Label();
		labelArtAplicables.setImmediate(false);
		labelArtAplicables.setWidth("-1px");
		labelArtAplicables.setHeight("-1px");
		labelArtAplicables.setValue("Artículos Aplicables:");
		LayoutInfoDenuncia.addComponent(labelArtAplicables, "top:400.0px;left:0.0px;");
		
		// campoArtAplicables
		campoArtAplicables = new TextField();
		campoArtAplicables.setImmediate(false);
		campoArtAplicables.setWidth("-1px");
		campoArtAplicables.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoArtAplicables, "top:440.0px;left:0.0px;");
		
		// labelFechaAudiencia
		labelFechaAudiencia = new Label();
		labelFechaAudiencia.setImmediate(false);
		labelFechaAudiencia.setWidth("-1px");
		labelFechaAudiencia.setHeight("-1px");
		labelFechaAudiencia.setValue("Fecha Audiencia:");
		LayoutInfoDenuncia.addComponent(labelFechaAudiencia, "top:400.0px;left:350.0px;");
		
		// campoFechaAudiencia
		campoFechaAudiencia = new TextField();
		campoFechaAudiencia.setImmediate(false);
		campoFechaAudiencia.setWidth("-1px");
		campoFechaAudiencia.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoFechaAudiencia, "top:440.0px;left:350.0px;");
		
		// labelHoraAudiencia
		labelHoraAudiencia = new Label();
		labelHoraAudiencia.setImmediate(false);
		labelHoraAudiencia.setWidth("-1px");
		labelHoraAudiencia.setHeight("-1px");
		labelHoraAudiencia.setValue("Hora Audiencia:");
		LayoutInfoDenuncia.addComponent(labelHoraAudiencia, "top:400.0px;left:700.0px;");
		
		// campoHoraAudiencia
		campoHoraAudiencia = new TextField();
		campoHoraAudiencia.setImmediate(false);
		campoHoraAudiencia.setWidth("-1px");
		campoHoraAudiencia.setHeight("-1px");
		LayoutInfoDenuncia.addComponent(campoHoraAudiencia, "top:440.0px;left:700.0px;");
		
		return LayoutInfoDenuncia;
	}

	@AutoGenerated
	private AbsoluteLayout buildLayoutUbicacion() {
		// common part: create layout
		LayoutUbicacion = new AbsoluteLayout();
		LayoutUbicacion.setImmediate(false);
		LayoutUbicacion.setWidth("100.0%");
		LayoutUbicacion.setHeight("100.0%");
		
		// labelUbicacion
		labelUbicacion = new Label();
		labelUbicacion.setImmediate(false);
		labelUbicacion.setWidth("-1px");
		labelUbicacion.setHeight("-1px");
		labelUbicacion.setValue("Ubicación:");
		LayoutUbicacion.addComponent(labelUbicacion, "top:0.0px;left:0.0px;");
		
		// campoUbicacion
		campoUbicacion = new TextField();
		campoUbicacion.setImmediate(false);
		campoUbicacion.setWidth("-1px");
		campoUbicacion.setHeight("-1px");
		LayoutUbicacion.addComponent(campoUbicacion, "top:40.0px;left:0.0px;");
		
		// labelMuebleUbicacion
		labelMuebleUbicacion = new Label();
		labelMuebleUbicacion.setImmediate(false);
		labelMuebleUbicacion.setWidth("-1px");
		labelMuebleUbicacion.setHeight("-1px");
		labelMuebleUbicacion.setValue("Mueble Ubicación:");
		LayoutUbicacion.addComponent(labelMuebleUbicacion, "top:0.0px;left:350.0px;");
		
		// campoMuebleUbicacion
		campoMuebleUbicacion = new TextField();
		campoMuebleUbicacion.setImmediate(false);
		campoMuebleUbicacion.setWidth("-1px");
		campoMuebleUbicacion.setHeight("-1px");
		LayoutUbicacion.addComponent(campoMuebleUbicacion, "top:40.0px;left:350.0px;");
		
		// labelUbicLegajos
		labelUbicLegajos = new Label();
		labelUbicLegajos.setImmediate(false);
		labelUbicLegajos.setWidth("-1px");
		labelUbicLegajos.setHeight("-1px");
		labelUbicLegajos.setValue("Ubicación Legajos:");
		LayoutUbicacion.addComponent(labelUbicLegajos, "top:0.0px;left:700.0px;");
		
		// campoUbicLegajos
		campoUbicLegajos = new TextField();
		campoUbicLegajos.setImmediate(false);
		campoUbicLegajos.setWidth("-1px");
		campoUbicLegajos.setHeight("-1px");
		LayoutUbicacion.addComponent(campoUbicLegajos, "top:40.0px;left:700.0px;");
		
		// labelCantLegajos
		labelCantLegajos = new Label();
		labelCantLegajos.setImmediate(false);
		labelCantLegajos.setWidth("-1px");
		labelCantLegajos.setHeight("-1px");
		labelCantLegajos.setValue("Cantidad de Legajos:");
		LayoutUbicacion.addComponent(labelCantLegajos, "top:200.0px;left:0.0px;");
		
		// campoCantLegajos
		campoCantLegajos = new TextField();
		campoCantLegajos.setImmediate(false);
		campoCantLegajos.setWidth("-1px");
		campoCantLegajos.setHeight("-1px");
		LayoutUbicacion.addComponent(campoCantLegajos, "top:240.0px;left:0.0px;");
		
		return LayoutUbicacion;
	}

	@AutoGenerated
	private AbsoluteLayout buildLayoutFechas() {
		// common part: create layout
		LayoutFechas = new AbsoluteLayout();
		LayoutFechas.setImmediate(false);
		LayoutFechas.setWidth("100.0%");
		LayoutFechas.setHeight("100.0%");
		
		// labelFechaUltUbicacion
		labelFechaUltUbicacion = new Label();
		labelFechaUltUbicacion.setImmediate(false);
		labelFechaUltUbicacion.setWidth("-1px");
		labelFechaUltUbicacion.setHeight("-1px");
		labelFechaUltUbicacion.setValue("Fecha Última Ubicación:");
		LayoutFechas.addComponent(labelFechaUltUbicacion, "top:0.0px;left:700.0px;");
		
		// campoFechaUltUbicacion
		campoFechaUltUbicacion = new TextField();
		campoFechaUltUbicacion.setImmediate(false);
		campoFechaUltUbicacion.setWidth("-1px");
		campoFechaUltUbicacion.setHeight("-1px");
		LayoutFechas.addComponent(campoFechaUltUbicacion, "top:40.0px;left:700.0px;");
		
		// labelFechaPresentacion
		labelFechaPresentacion = new Label();
		labelFechaPresentacion.setImmediate(false);
		labelFechaPresentacion.setWidth("-1px");
		labelFechaPresentacion.setHeight("-1px");
		labelFechaPresentacion.setValue("Fecha Presentación:");
		LayoutFechas.addComponent(labelFechaPresentacion, "top:0.0px;");
		
		// campoFechaPresentacion
		campoFechaPresentacion = new TextField();
		campoFechaPresentacion.setImmediate(false);
		campoFechaPresentacion.setWidth("-1px");
		campoFechaPresentacion.setHeight("-1px");
		LayoutFechas.addComponent(campoFechaPresentacion, "top:40.0px;left:0.0px;");
		
		// labelFechaIng
		labelFechaIng = new Label();
		labelFechaIng.setImmediate(false);
		labelFechaIng.setWidth("-1px");
		labelFechaIng.setHeight("-1px");
		labelFechaIng.setValue("Fecha Ingreso Denuncia:");
		LayoutFechas.addComponent(labelFechaIng, "top:0.0px;left:350.0px;");
		
		// campoFechaIng
		campoFechaIng = new TextField();
		campoFechaIng.setImmediate(false);
		campoFechaIng.setWidth("-1px");
		campoFechaIng.setHeight("-1px");
		LayoutFechas.addComponent(campoFechaIng, "top:40.0px;left:350.0px;");
		
		// campoDuracCambioUltUbic
		campoDuracCambioUltUbic = new TextField();
		campoDuracCambioUltUbic.setImmediate(false);
		campoDuracCambioUltUbic.setWidth("-1px");
		campoDuracCambioUltUbic.setHeight("-1px");
		LayoutFechas.addComponent(campoDuracCambioUltUbic, "top:730.0px;left:0.0px;");
		
		return LayoutFechas;
	}

}
