package ucr.casoUso;

import java.sql.SQLException;
import java.util.ResourceBundle.Control;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.sqlcontainer.SQLContainer;
import com.vaadin.data.util.sqlcontainer.connection.SimpleJDBCConnectionPool;
import com.vaadin.data.util.sqlcontainer.query.FreeformQuery;
import com.vaadin.event.FieldEvents.TextChangeEvent;
import com.vaadin.event.FieldEvents.TextChangeListener;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;

public class VistaListaExpedientesArchivados extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private ComboBox comboBoxOpciones;
	@AutoGenerated
	private TextField textFieldFiltro;
	@AutoGenerated
	private Table tableExpArc;
	@AutoGenerated
	private Button buttonVolver;
	@AutoGenerated
	private Label labelTitulo;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	private String nomColum = null;
	private String valorText = null;
	private Controlador control;
	private ControladorListaExpedientesArchivados controlador;
	private final String consultaInicial = "SELECT codigo, numexpediente, instructorasig,fechaingreso, clasificacion "
			+ "FROM expediente "
			+ "WHERE archivado = true";
	
	public VistaListaExpedientesArchivados() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		llenarTabla(consultaInicial);
		llenarComboBoxOpciones();
		control = Controlador.obtenerInstancia();
		
		//Metodo para el filtro de la tabla
		textFieldFiltro.addTextChangeListener(new TextChangeListener() {
            @Override
            public void textChange(TextChangeEvent event) {
            	String tabla = "";
            	if (comboBoxOpciones.getValue() != null){
            	switch(comboBoxOpciones.getValue().toString()) {
            		case "Código":
            			tabla = "codigo";
            			break;
            		case "Número de Expediente":
            			tabla = "numexpediente";
            			break;
            		case "Instructor Asignado":
            			tabla = "instructorasig";
            			break;
            		case "Fecha de Ingreso":
            			tabla = "fechaingreso";
            			break;
            		case "Clasificación":
            			tabla = "clasificacion";
            			break;
            	}
            	String filtro = event.getText();
                String consulta;
                	tableExpArc.removeAllItems();
        			if (event.getText().isEmpty()) {
        				llenarTabla(consultaInicial);
        			}
        			else {
        				consulta = consultaInicial + " AND " + tabla + " LIKE " + "'%" + filtro + "%'";
        				llenarTabla(consulta);
        			}
            }
            }
        });

		buttonVolver.addClickListener(new ClickListener(){
			@Override
			public void buttonClick (ClickEvent evento){
				control.cambiarVista("Menu Principal");
			}
		});
	}
	
	public void llenarTabla(String hileraConsulta){
		try{
			SimpleJDBCConnectionPool cp;
			cp = new SimpleJDBCConnectionPool("org.postgresql.Driver",
				"jdbc:postgresql://127.0.0.1:5432/Fiscalia", "postgres", "ECCIpgsql2016", 1, 5);
			//TableQuery tq = new TableQuery("expediente", cp);
			//SQLContainer containerTabla = new SQLContainer(tq);
			FreeformQuery productFreeFormQuery = new FreeformQuery(hileraConsulta, cp);
			SQLContainer containerTabla = new SQLContainer(productFreeFormQuery);
			tableExpArc.setContainerDataSource(containerTabla);
			tableExpArc.setSelectable(true);
			tableExpArc.setImmediate(true);
			tableExpArc.setVisibleColumns(new Object[] {"codigo","numexpediente","instructorasig","fechaingreso","clasificacion"});
			tableExpArc.setColumnHeaders(new String [] {"Código", "Número de Expediente", "Instructor Asignado", "Fecha de Ingreso", "Clasificación"});
			tableExpArc.setColumnReorderingAllowed(true);
			tableExpArc.setColumnCollapsingAllowed(true);	
		}
		catch (SQLException e){
			e.printStackTrace();
		}
	}
	
	private void llenarComboBoxOpciones() {
		comboBoxOpciones.addItem("Código");
		comboBoxOpciones.addItem("Número de Expediente");
		comboBoxOpciones.addItem("Instructor Asignado");
		comboBoxOpciones.addItem("Fecha de Ingreso");
		comboBoxOpciones.addItem("Clasificación");
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// labelTitulo
		labelTitulo = new Label();
		labelTitulo.setImmediate(false);
		labelTitulo.setWidth("200px");
		labelTitulo.setHeight("-1px");
		labelTitulo.setValue("Lista de Expedientes Archivados");
		mainLayout.addComponent(labelTitulo, "top:100.0px;left:120.0px;");
		
		// buttonVolver
		buttonVolver = new Button();
		buttonVolver.setCaption("Volver");
		buttonVolver.setImmediate(true);
		buttonVolver.setWidth("-1px");
		buttonVolver.setHeight("-1px");
		mainLayout.addComponent(buttonVolver, "top:460.0px;left:140.0px;");
		
		// tableExpArc
		tableExpArc = new Table();
		tableExpArc.setImmediate(false);
		tableExpArc.setWidth("100.0%");
		tableExpArc.setHeight("240px");
		mainLayout.addComponent(tableExpArc, "top:120.0px;right:509.0px;left:120.0px;");
		
		// textFieldFiltro
		textFieldFiltro = new TextField();
		textFieldFiltro.setImmediate(false);
		textFieldFiltro.setWidth("140px");
		textFieldFiltro.setHeight("-1px");
		mainLayout.addComponent(textFieldFiltro, "top:400.0px;left:120.0px;");
		
		// comboBoxOpciones
		comboBoxOpciones = new ComboBox();
		comboBoxOpciones.setImmediate(false);
		comboBoxOpciones.setWidth("220px");
		comboBoxOpciones.setHeight("-1px");
		mainLayout.addComponent(comboBoxOpciones, "top:400.0px;left:300.0px;");
		
		return mainLayout;
	}

}
